// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action_common/file_event.proto

#include "action_common/file_event.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace verteilen2 {
namespace action {
namespace common {
PROTOBUF_CONSTEXPR FileEvent::FileEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.fs_uuid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.filename_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FileEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileEventDefaultTypeInternal() {}
  union {
    FileEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileEventDefaultTypeInternal _FileEvent_default_instance_;
}  // namespace common
}  // namespace action
}  // namespace verteilen2
static ::_pb::Metadata file_level_metadata_action_5fcommon_2ffile_5fevent_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_action_5fcommon_2ffile_5fevent_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_action_5fcommon_2ffile_5fevent_2eproto = nullptr;

const uint32_t TableStruct_action_5fcommon_2ffile_5fevent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::verteilen2::action::common::FileEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::verteilen2::action::common::FileEvent, _impl_.fs_uuid_),
  PROTOBUF_FIELD_OFFSET(::verteilen2::action::common::FileEvent, _impl_.filename_),
  PROTOBUF_FIELD_OFFSET(::verteilen2::action::common::FileEvent, _impl_.type_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::verteilen2::action::common::FileEvent)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::verteilen2::action::common::_FileEvent_default_instance_._instance,
};

const char descriptor_table_protodef_action_5fcommon_2ffile_5fevent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036action_common/file_event.proto\022\030vertei"
  "len2.action.common\032\032enum/file_event_type"
  ".proto\"W\n\tFileEvent\022\017\n\007fs_uuid\030\001 \001(\t\022\020\n\010"
  "filename\030\002 \001(\t\022\'\n\004type\030\003 \001(\0162\031.verteilen"
  "2.FileEventTypeb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_action_5fcommon_2ffile_5fevent_2eproto_deps[1] = {
  &::descriptor_table_enum_2ffile_5fevent_5ftype_2eproto,
};
static ::_pbi::once_flag descriptor_table_action_5fcommon_2ffile_5fevent_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_action_5fcommon_2ffile_5fevent_2eproto = {
    false, false, 183, descriptor_table_protodef_action_5fcommon_2ffile_5fevent_2eproto,
    "action_common/file_event.proto",
    &descriptor_table_action_5fcommon_2ffile_5fevent_2eproto_once, descriptor_table_action_5fcommon_2ffile_5fevent_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_action_5fcommon_2ffile_5fevent_2eproto::offsets,
    file_level_metadata_action_5fcommon_2ffile_5fevent_2eproto, file_level_enum_descriptors_action_5fcommon_2ffile_5fevent_2eproto,
    file_level_service_descriptors_action_5fcommon_2ffile_5fevent_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_action_5fcommon_2ffile_5fevent_2eproto_getter() {
  return &descriptor_table_action_5fcommon_2ffile_5fevent_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_action_5fcommon_2ffile_5fevent_2eproto(&descriptor_table_action_5fcommon_2ffile_5fevent_2eproto);
namespace verteilen2 {
namespace action {
namespace common {

// ===================================================================

class FileEvent::_Internal {
 public:
};

FileEvent::FileEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:verteilen2.action.common.FileEvent)
}
FileEvent::FileEvent(const FileEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FileEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.fs_uuid_){}
    , decltype(_impl_.filename_){}
    , decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.fs_uuid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fs_uuid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_fs_uuid().empty()) {
    _this->_impl_.fs_uuid_.Set(from._internal_fs_uuid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filename().empty()) {
    _this->_impl_.filename_.Set(from._internal_filename(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.type_ = from._impl_.type_;
  // @@protoc_insertion_point(copy_constructor:verteilen2.action.common.FileEvent)
}

inline void FileEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.fs_uuid_){}
    , decltype(_impl_.filename_){}
    , decltype(_impl_.type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.fs_uuid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fs_uuid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FileEvent::~FileEvent() {
  // @@protoc_insertion_point(destructor:verteilen2.action.common.FileEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FileEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.fs_uuid_.Destroy();
  _impl_.filename_.Destroy();
}

void FileEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FileEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:verteilen2.action.common.FileEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.fs_uuid_.ClearToEmpty();
  _impl_.filename_.ClearToEmpty();
  _impl_.type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FileEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string fs_uuid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_fs_uuid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "verteilen2.action.common.FileEvent.fs_uuid"));
        } else
          goto handle_unusual;
        continue;
      // string filename = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_filename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "verteilen2.action.common.FileEvent.filename"));
        } else
          goto handle_unusual;
        continue;
      // .verteilen2.FileEventType type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::verteilen2::FileEventType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FileEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:verteilen2.action.common.FileEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string fs_uuid = 1;
  if (!this->_internal_fs_uuid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fs_uuid().data(), static_cast<int>(this->_internal_fs_uuid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "verteilen2.action.common.FileEvent.fs_uuid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_fs_uuid(), target);
  }

  // string filename = 2;
  if (!this->_internal_filename().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filename().data(), static_cast<int>(this->_internal_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "verteilen2.action.common.FileEvent.filename");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_filename(), target);
  }

  // .verteilen2.FileEventType type = 3;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:verteilen2.action.common.FileEvent)
  return target;
}

size_t FileEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:verteilen2.action.common.FileEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string fs_uuid = 1;
  if (!this->_internal_fs_uuid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fs_uuid());
  }

  // string filename = 2;
  if (!this->_internal_filename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filename());
  }

  // .verteilen2.FileEventType type = 3;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FileEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FileEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FileEvent::GetClassData() const { return &_class_data_; }


void FileEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FileEvent*>(&to_msg);
  auto& from = static_cast<const FileEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:verteilen2.action.common.FileEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_fs_uuid().empty()) {
    _this->_internal_set_fs_uuid(from._internal_fs_uuid());
  }
  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FileEvent::CopyFrom(const FileEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:verteilen2.action.common.FileEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FileEvent::IsInitialized() const {
  return true;
}

void FileEvent::InternalSwap(FileEvent* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.fs_uuid_, lhs_arena,
      &other->_impl_.fs_uuid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filename_, lhs_arena,
      &other->_impl_.filename_, rhs_arena
  );
  swap(_impl_.type_, other->_impl_.type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FileEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_action_5fcommon_2ffile_5fevent_2eproto_getter, &descriptor_table_action_5fcommon_2ffile_5fevent_2eproto_once,
      file_level_metadata_action_5fcommon_2ffile_5fevent_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace action
}  // namespace verteilen2
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::verteilen2::action::common::FileEvent*
Arena::CreateMaybeMessage< ::verteilen2::action::common::FileEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::verteilen2::action::common::FileEvent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
