load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "common_lib",
    srcs = glob(
        ["src/*.cc", "src/*.cpp", "src/*.c"], 
        allow_empty = True
    ),
    hdrs = glob(
        ["include/*.h", "include/*.hpp", "include/*.hh"], 
        allow_empty = True
    ),
    includes = [
        "include",
        "include/verteilen2/proto_gen",
        "verteilen2/proto_gen",
    ],
    deps = [
        "//lib/libhv:hv",
        "//lib/uuid:stduuid",
        "//lib/sqlite:sqlite3",
        "//lib/sqlite:SQLiteCpp",
        "//lib/efsw:efsw",
        "//lib/json:json",
        "//lib/grpc:grpc",
    ],
    visibility = ["//visibility:public"],
)