module(
    name = "verteilen2",
    version = "0.0.0",
)

version_ext = use_extension("//:extensions.bzl", "version_ext")
use_repo(version_ext, "project_version")

bazel_dep(name = "rules_cc", version = "0.2.22")

bazel_dep(name = "grpc", version = "1.83.0")
bazel_dep(name = "crowcpp", version = "1.3.0")
bazel_dep(name = "argparse", version = "3.2.0")
bazel_dep(name = "spdlog", version = "1.17.0")
bazel_dep(name = "ftxui", version = "7.0.1")
bazel_dep(name = "cpp-sqlite", version = "0.0.0-20241111-21be8b5")
bazel_dep(name = "jsoncpp", version = "1.9.6.bcr.2")
bazel_dep(name = "abseil-cpp", version = "20260526.0")
bazel_dep(name = "curl", version = "8.12.0.bcr.1")
bazel_dep(name = "googletest", version = "1.17.0.bcr.2")
