// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum/status.proto

#include "enum/status.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace verteilen2 {
}  // namespace verteilen2
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_enum_2fstatus_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_enum_2fstatus_2eproto = nullptr;
const uint32_t TableStruct_enum_2fstatus_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_enum_2fstatus_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021enum/status.proto\022\nverteilen2*6\n\006Statu"
  "s\022\010\n\004NONE\020\000\022\013\n\007SUCCESS\020\001\022\n\n\006FAILED\020\002\022\t\n\005"
  "OTHER\020\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_enum_2fstatus_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_enum_2fstatus_2eproto = {
    false, false, 95, descriptor_table_protodef_enum_2fstatus_2eproto,
    "enum/status.proto",
    &descriptor_table_enum_2fstatus_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_enum_2fstatus_2eproto::offsets,
    nullptr, file_level_enum_descriptors_enum_2fstatus_2eproto,
    file_level_service_descriptors_enum_2fstatus_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_enum_2fstatus_2eproto_getter() {
  return &descriptor_table_enum_2fstatus_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_enum_2fstatus_2eproto(&descriptor_table_enum_2fstatus_2eproto);
namespace verteilen2 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Status_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enum_2fstatus_2eproto);
  return file_level_enum_descriptors_enum_2fstatus_2eproto[0];
}
bool Status_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace verteilen2
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
