load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "client_app",
    srcs = glob(
        [
            "src/*.cc", "src/*.cpp", "src/*.c",
            "include/*.h", "include/*.hpp", "include/*.hh",
        ], 
        allow_empty = True
    ),
    deps = [
        "//src/native/common:common_lib",
    ],
    includes = [
        "include",
        "//src/native/client/include",
        "//src/native/common/include",
        "//src/native/common/include/verteilen2/proto_gen",
        "//lib/argh",
        "//lib/json/include",
        "//lib/efsw/include",
        "//lib/crow/include",
        "//lib/mdns/include",
        "//lib/sqlite/include",
        "//lib/spdlog/include",
        "//lib/libhv/include",
        "//lib/grpc/include",
    ],
    visibility = ["//visibility:public"],
)