// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cron.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cron_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cron_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "data_field.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cron_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cron_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cron_2eproto;
namespace verteilen2 {
class Cron;
struct CronDefaultTypeInternal;
extern CronDefaultTypeInternal _Cron_default_instance_;
}  // namespace verteilen2
PROTOBUF_NAMESPACE_OPEN
template<> ::verteilen2::Cron* Arena::CreateMaybeMessage<::verteilen2::Cron>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace verteilen2 {

// ===================================================================

class Cron final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:verteilen2.Cron) */ {
 public:
  inline Cron() : Cron(nullptr) {}
  ~Cron() override;
  explicit PROTOBUF_CONSTEXPR Cron(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Cron(const Cron& from);
  Cron(Cron&& from) noexcept
    : Cron() {
    *this = ::std::move(from);
  }

  inline Cron& operator=(const Cron& from) {
    CopyFrom(from);
    return *this;
  }
  inline Cron& operator=(Cron&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Cron& default_instance() {
    return *internal_default_instance();
  }
  static inline const Cron* internal_default_instance() {
    return reinterpret_cast<const Cron*>(
               &_Cron_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Cron& a, Cron& b) {
    a.Swap(&b);
  }
  inline void Swap(Cron* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Cron* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Cron* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Cron>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Cron& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Cron& from) {
    Cron::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Cron* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "verteilen2.Cron";
  }
  protected:
  explicit Cron(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUuidFieldNumber = 1,
    kNameFieldNumber = 2,
    kDescriptionFieldNumber = 3,
    kProjectFieldNumber = 4,
  };
  // string uuid = 1;
  void clear_uuid();
  const std::string& uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string description = 3;
  void clear_description();
  const std::string& description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_description();
  PROTOBUF_NODISCARD std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // .verteilen2.DataField project = 4;
  bool has_project() const;
  private:
  bool _internal_has_project() const;
  public:
  void clear_project();
  const ::verteilen2::DataField& project() const;
  PROTOBUF_NODISCARD ::verteilen2::DataField* release_project();
  ::verteilen2::DataField* mutable_project();
  void set_allocated_project(::verteilen2::DataField* project);
  private:
  const ::verteilen2::DataField& _internal_project() const;
  ::verteilen2::DataField* _internal_mutable_project();
  public:
  void unsafe_arena_set_allocated_project(
      ::verteilen2::DataField* project);
  ::verteilen2::DataField* unsafe_arena_release_project();

  // @@protoc_insertion_point(class_scope:verteilen2.Cron)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
    ::verteilen2::DataField* project_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cron_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Cron

// string uuid = 1;
inline void Cron::clear_uuid() {
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& Cron::uuid() const {
  // @@protoc_insertion_point(field_get:verteilen2.Cron.uuid)
  return _internal_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Cron::set_uuid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.uuid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Cron.uuid)
}
inline std::string* Cron::mutable_uuid() {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:verteilen2.Cron.uuid)
  return _s;
}
inline const std::string& Cron::_internal_uuid() const {
  return _impl_.uuid_.Get();
}
inline void Cron::_internal_set_uuid(const std::string& value) {
  
  _impl_.uuid_.Set(value, GetArenaForAllocation());
}
inline std::string* Cron::_internal_mutable_uuid() {
  
  return _impl_.uuid_.Mutable(GetArenaForAllocation());
}
inline std::string* Cron::release_uuid() {
  // @@protoc_insertion_point(field_release:verteilen2.Cron.uuid)
  return _impl_.uuid_.Release();
}
inline void Cron::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  _impl_.uuid_.SetAllocated(uuid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Cron.uuid)
}

// string name = 2;
inline void Cron::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Cron::name() const {
  // @@protoc_insertion_point(field_get:verteilen2.Cron.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Cron::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Cron.name)
}
inline std::string* Cron::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:verteilen2.Cron.name)
  return _s;
}
inline const std::string& Cron::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Cron::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Cron::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Cron::release_name() {
  // @@protoc_insertion_point(field_release:verteilen2.Cron.name)
  return _impl_.name_.Release();
}
inline void Cron::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Cron.name)
}

// string description = 3;
inline void Cron::clear_description() {
  _impl_.description_.ClearToEmpty();
}
inline const std::string& Cron::description() const {
  // @@protoc_insertion_point(field_get:verteilen2.Cron.description)
  return _internal_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Cron::set_description(ArgT0&& arg0, ArgT... args) {
 
 _impl_.description_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Cron.description)
}
inline std::string* Cron::mutable_description() {
  std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:verteilen2.Cron.description)
  return _s;
}
inline const std::string& Cron::_internal_description() const {
  return _impl_.description_.Get();
}
inline void Cron::_internal_set_description(const std::string& value) {
  
  _impl_.description_.Set(value, GetArenaForAllocation());
}
inline std::string* Cron::_internal_mutable_description() {
  
  return _impl_.description_.Mutable(GetArenaForAllocation());
}
inline std::string* Cron::release_description() {
  // @@protoc_insertion_point(field_release:verteilen2.Cron.description)
  return _impl_.description_.Release();
}
inline void Cron::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  _impl_.description_.SetAllocated(description, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.description_.IsDefault()) {
    _impl_.description_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Cron.description)
}

// .verteilen2.DataField project = 4;
inline bool Cron::_internal_has_project() const {
  return this != internal_default_instance() && _impl_.project_ != nullptr;
}
inline bool Cron::has_project() const {
  return _internal_has_project();
}
inline const ::verteilen2::DataField& Cron::_internal_project() const {
  const ::verteilen2::DataField* p = _impl_.project_;
  return p != nullptr ? *p : reinterpret_cast<const ::verteilen2::DataField&>(
      ::verteilen2::_DataField_default_instance_);
}
inline const ::verteilen2::DataField& Cron::project() const {
  // @@protoc_insertion_point(field_get:verteilen2.Cron.project)
  return _internal_project();
}
inline void Cron::unsafe_arena_set_allocated_project(
    ::verteilen2::DataField* project) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.project_);
  }
  _impl_.project_ = project;
  if (project) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:verteilen2.Cron.project)
}
inline ::verteilen2::DataField* Cron::release_project() {
  
  ::verteilen2::DataField* temp = _impl_.project_;
  _impl_.project_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::verteilen2::DataField* Cron::unsafe_arena_release_project() {
  // @@protoc_insertion_point(field_release:verteilen2.Cron.project)
  
  ::verteilen2::DataField* temp = _impl_.project_;
  _impl_.project_ = nullptr;
  return temp;
}
inline ::verteilen2::DataField* Cron::_internal_mutable_project() {
  
  if (_impl_.project_ == nullptr) {
    auto* p = CreateMaybeMessage<::verteilen2::DataField>(GetArenaForAllocation());
    _impl_.project_ = p;
  }
  return _impl_.project_;
}
inline ::verteilen2::DataField* Cron::mutable_project() {
  ::verteilen2::DataField* _msg = _internal_mutable_project();
  // @@protoc_insertion_point(field_mutable:verteilen2.Cron.project)
  return _msg;
}
inline void Cron::set_allocated_project(::verteilen2::DataField* project) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.project_);
  }
  if (project) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(project));
    if (message_arena != submessage_arena) {
      project = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, project, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.project_ = project;
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Cron.project)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace verteilen2

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cron_2eproto
