/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: data_field.proto */

#ifndef PROTOBUF_C_data_5ffield_2eproto__INCLUDED
#define PROTOBUF_C_data_5ffield_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Verteilen2__DataField Verteilen2__DataField;


/* --- enums --- */


/* --- messages --- */

struct  Verteilen2__DataField
{
  ProtobufCMessage base;
  char *uuid;
  protobuf_c_boolean vaild;
};
#define VERTEILEN2__DATA_FIELD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__data_field__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


/* Verteilen2__DataField methods */
void   verteilen2__data_field__init
                     (Verteilen2__DataField         *message);
size_t verteilen2__data_field__get_packed_size
                     (const Verteilen2__DataField   *message);
size_t verteilen2__data_field__pack
                     (const Verteilen2__DataField   *message,
                      uint8_t             *out);
size_t verteilen2__data_field__pack_to_buffer
                     (const Verteilen2__DataField   *message,
                      ProtobufCBuffer     *buffer);
Verteilen2__DataField *
       verteilen2__data_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   verteilen2__data_field__free_unpacked
                     (Verteilen2__DataField *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Verteilen2__DataField_Closure)
                 (const Verteilen2__DataField *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor verteilen2__data_field__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_data_5ffield_2eproto__INCLUDED */
