/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: file_system_rule.proto */

#ifndef PROTOBUF_C_file_5fsystem_5frule_2eproto__INCLUDED
#define PROTOBUF_C_file_5fsystem_5frule_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Verteilen2__FileSystemRule Verteilen2__FileSystemRule;


/* --- enums --- */

typedef enum _Verteilen2__SyncType {
  VERTEILEN2__SYNC_TYPE__NONE = 0,
  VERTEILEN2__SYNC_TYPE__CREATE = 1,
  VERTEILEN2__SYNC_TYPE__MODIFY = 2,
  VERTEILEN2__SYNC_TYPE__DELETE = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(VERTEILEN2__SYNC_TYPE)
} Verteilen2__SyncType;

/* --- messages --- */

/*
 * MsgType: DEBUG_LOG
 */
struct  Verteilen2__FileSystemRule
{
  ProtobufCMessage base;
  char *uuid;
  char *target_uuid;
  char *filename;
  Verteilen2__SyncType type;
};
#define VERTEILEN2__FILE_SYSTEM_RULE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__file_system_rule__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, VERTEILEN2__SYNC_TYPE__NONE }


/* Verteilen2__FileSystemRule methods */
void   verteilen2__file_system_rule__init
                     (Verteilen2__FileSystemRule         *message);
size_t verteilen2__file_system_rule__get_packed_size
                     (const Verteilen2__FileSystemRule   *message);
size_t verteilen2__file_system_rule__pack
                     (const Verteilen2__FileSystemRule   *message,
                      uint8_t             *out);
size_t verteilen2__file_system_rule__pack_to_buffer
                     (const Verteilen2__FileSystemRule   *message,
                      ProtobufCBuffer     *buffer);
Verteilen2__FileSystemRule *
       verteilen2__file_system_rule__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   verteilen2__file_system_rule__free_unpacked
                     (Verteilen2__FileSystemRule *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Verteilen2__FileSystemRule_Closure)
                 (const Verteilen2__FileSystemRule *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    verteilen2__sync_type__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__file_system_rule__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_file_5fsystem_5frule_2eproto__INCLUDED */
