// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action_common/file_event.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_action_5fcommon_2ffile_5fevent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_action_5fcommon_2ffile_5fevent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "enum/file_event_type.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_action_5fcommon_2ffile_5fevent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_action_5fcommon_2ffile_5fevent_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_action_5fcommon_2ffile_5fevent_2eproto;
namespace verteilen2 {
namespace action {
namespace common {
class FileEvent;
struct FileEventDefaultTypeInternal;
extern FileEventDefaultTypeInternal _FileEvent_default_instance_;
}  // namespace common
}  // namespace action
}  // namespace verteilen2
PROTOBUF_NAMESPACE_OPEN
template<> ::verteilen2::action::common::FileEvent* Arena::CreateMaybeMessage<::verteilen2::action::common::FileEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace verteilen2 {
namespace action {
namespace common {

// ===================================================================

class FileEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:verteilen2.action.common.FileEvent) */ {
 public:
  inline FileEvent() : FileEvent(nullptr) {}
  ~FileEvent() override;
  explicit PROTOBUF_CONSTEXPR FileEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileEvent(const FileEvent& from);
  FileEvent(FileEvent&& from) noexcept
    : FileEvent() {
    *this = ::std::move(from);
  }

  inline FileEvent& operator=(const FileEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileEvent& operator=(FileEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileEvent* internal_default_instance() {
    return reinterpret_cast<const FileEvent*>(
               &_FileEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FileEvent& a, FileEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(FileEvent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileEvent& from) {
    FileEvent::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileEvent* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "verteilen2.action.common.FileEvent";
  }
  protected:
  explicit FileEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFsUuidFieldNumber = 1,
    kFilenameFieldNumber = 2,
    kTypeFieldNumber = 3,
  };
  // string fs_uuid = 1;
  void clear_fs_uuid();
  const std::string& fs_uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_fs_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_fs_uuid();
  PROTOBUF_NODISCARD std::string* release_fs_uuid();
  void set_allocated_fs_uuid(std::string* fs_uuid);
  private:
  const std::string& _internal_fs_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fs_uuid(const std::string& value);
  std::string* _internal_mutable_fs_uuid();
  public:

  // string filename = 2;
  void clear_filename();
  const std::string& filename() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filename(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // .verteilen2.FileEventType type = 3;
  void clear_type();
  ::verteilen2::FileEventType type() const;
  void set_type(::verteilen2::FileEventType value);
  private:
  ::verteilen2::FileEventType _internal_type() const;
  void _internal_set_type(::verteilen2::FileEventType value);
  public:

  // @@protoc_insertion_point(class_scope:verteilen2.action.common.FileEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fs_uuid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_action_5fcommon_2ffile_5fevent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FileEvent

// string fs_uuid = 1;
inline void FileEvent::clear_fs_uuid() {
  _impl_.fs_uuid_.ClearToEmpty();
}
inline const std::string& FileEvent::fs_uuid() const {
  // @@protoc_insertion_point(field_get:verteilen2.action.common.FileEvent.fs_uuid)
  return _internal_fs_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileEvent::set_fs_uuid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.fs_uuid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.action.common.FileEvent.fs_uuid)
}
inline std::string* FileEvent::mutable_fs_uuid() {
  std::string* _s = _internal_mutable_fs_uuid();
  // @@protoc_insertion_point(field_mutable:verteilen2.action.common.FileEvent.fs_uuid)
  return _s;
}
inline const std::string& FileEvent::_internal_fs_uuid() const {
  return _impl_.fs_uuid_.Get();
}
inline void FileEvent::_internal_set_fs_uuid(const std::string& value) {
  
  _impl_.fs_uuid_.Set(value, GetArenaForAllocation());
}
inline std::string* FileEvent::_internal_mutable_fs_uuid() {
  
  return _impl_.fs_uuid_.Mutable(GetArenaForAllocation());
}
inline std::string* FileEvent::release_fs_uuid() {
  // @@protoc_insertion_point(field_release:verteilen2.action.common.FileEvent.fs_uuid)
  return _impl_.fs_uuid_.Release();
}
inline void FileEvent::set_allocated_fs_uuid(std::string* fs_uuid) {
  if (fs_uuid != nullptr) {
    
  } else {
    
  }
  _impl_.fs_uuid_.SetAllocated(fs_uuid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.fs_uuid_.IsDefault()) {
    _impl_.fs_uuid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.action.common.FileEvent.fs_uuid)
}

// string filename = 2;
inline void FileEvent::clear_filename() {
  _impl_.filename_.ClearToEmpty();
}
inline const std::string& FileEvent::filename() const {
  // @@protoc_insertion_point(field_get:verteilen2.action.common.FileEvent.filename)
  return _internal_filename();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileEvent::set_filename(ArgT0&& arg0, ArgT... args) {
 
 _impl_.filename_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.action.common.FileEvent.filename)
}
inline std::string* FileEvent::mutable_filename() {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:verteilen2.action.common.FileEvent.filename)
  return _s;
}
inline const std::string& FileEvent::_internal_filename() const {
  return _impl_.filename_.Get();
}
inline void FileEvent::_internal_set_filename(const std::string& value) {
  
  _impl_.filename_.Set(value, GetArenaForAllocation());
}
inline std::string* FileEvent::_internal_mutable_filename() {
  
  return _impl_.filename_.Mutable(GetArenaForAllocation());
}
inline std::string* FileEvent::release_filename() {
  // @@protoc_insertion_point(field_release:verteilen2.action.common.FileEvent.filename)
  return _impl_.filename_.Release();
}
inline void FileEvent::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  _impl_.filename_.SetAllocated(filename, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.action.common.FileEvent.filename)
}

// .verteilen2.FileEventType type = 3;
inline void FileEvent::clear_type() {
  _impl_.type_ = 0;
}
inline ::verteilen2::FileEventType FileEvent::_internal_type() const {
  return static_cast< ::verteilen2::FileEventType >(_impl_.type_);
}
inline ::verteilen2::FileEventType FileEvent::type() const {
  // @@protoc_insertion_point(field_get:verteilen2.action.common.FileEvent.type)
  return _internal_type();
}
inline void FileEvent::_internal_set_type(::verteilen2::FileEventType value) {
  
  _impl_.type_ = value;
}
inline void FileEvent::set_type(::verteilen2::FileEventType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:verteilen2.action.common.FileEvent.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace action
}  // namespace verteilen2

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_action_5fcommon_2ffile_5fevent_2eproto
