/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: file_system.proto */

#ifndef PROTOBUF_C_file_5fsystem_2eproto__INCLUDED
#define PROTOBUF_C_file_5fsystem_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "file_system_rule.pb-c.h"

typedef struct Verteilen2__FileSystem Verteilen2__FileSystem;


/* --- enums --- */


/* --- messages --- */

/*
 * MsgType: DEBUG_LOG
 */
struct  Verteilen2__FileSystem
{
  ProtobufCMessage base;
  char *uuid;
  char *title;
  char *description;
  size_t n_rules;
  Verteilen2__FileSystemRule **rules;
};
#define VERTEILEN2__FILE_SYSTEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__file_system__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


/* Verteilen2__FileSystem methods */
void   verteilen2__file_system__init
                     (Verteilen2__FileSystem         *message);
size_t verteilen2__file_system__get_packed_size
                     (const Verteilen2__FileSystem   *message);
size_t verteilen2__file_system__pack
                     (const Verteilen2__FileSystem   *message,
                      uint8_t             *out);
size_t verteilen2__file_system__pack_to_buffer
                     (const Verteilen2__FileSystem   *message,
                      ProtobufCBuffer     *buffer);
Verteilen2__FileSystem *
       verteilen2__file_system__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   verteilen2__file_system__free_unpacked
                     (Verteilen2__FileSystem *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Verteilen2__FileSystem_Closure)
                 (const Verteilen2__FileSystem *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor verteilen2__file_system__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_file_5fsystem_2eproto__INCLUDED */
