/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: header.proto */

#ifndef PROTOBUF_C_header_2eproto__INCLUDED
#define PROTOBUF_C_header_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Verteilen2__RawData Verteilen2__RawData;


/* --- enums --- */

typedef enum _Verteilen2__MsgType {
  VERTEILEN2__MSG_TYPE__UNKNOWN = 0,
  VERTEILEN2__MSG_TYPE__DEBUG_LOG = 1,
  VERTEILEN2__MSG_TYPE__EXECUTE_JOB = 2,
  VERTEILEN2__MSG_TYPE__DEPLOY_SERVICE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(VERTEILEN2__MSG_TYPE)
} Verteilen2__MsgType;

/* --- messages --- */

struct  Verteilen2__RawData
{
  ProtobufCMessage base;
  Verteilen2__MsgType type;
  ProtobufCBinaryData data;
};
#define VERTEILEN2__RAW_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__raw_data__descriptor) \
    , VERTEILEN2__MSG_TYPE__UNKNOWN, {0,NULL} }


/* Verteilen2__RawData methods */
void   verteilen2__raw_data__init
                     (Verteilen2__RawData         *message);
size_t verteilen2__raw_data__get_packed_size
                     (const Verteilen2__RawData   *message);
size_t verteilen2__raw_data__pack
                     (const Verteilen2__RawData   *message,
                      uint8_t             *out);
size_t verteilen2__raw_data__pack_to_buffer
                     (const Verteilen2__RawData   *message,
                      ProtobufCBuffer     *buffer);
Verteilen2__RawData *
       verteilen2__raw_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   verteilen2__raw_data__free_unpacked
                     (Verteilen2__RawData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Verteilen2__RawData_Closure)
                 (const Verteilen2__RawData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    verteilen2__msg_type__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__raw_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_header_2eproto__INCLUDED */
