/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: job.proto */

#ifndef PROTOBUF_C_job_2eproto__INCLUDED
#define PROTOBUF_C_job_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "dynamic_map.pb-c.h"

typedef struct Verteilen2__Job Verteilen2__Job;


/* --- enums --- */


/* --- messages --- */

/*
 * MsgType: DEBUG_LOG
 */
struct  Verteilen2__Job
{
  ProtobufCMessage base;
  char *uuid;
  char *name;
  int32_t type;
  char *script;
  Verteilen2__DynamicMap *d_map;
  char *inputs_0;
  char *inputs_1;
  char *inputs_2;
  char *inputs_3;
  char *inputs_4;
};
#define VERTEILEN2__JOB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__job__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Verteilen2__Job methods */
void   verteilen2__job__init
                     (Verteilen2__Job         *message);
size_t verteilen2__job__get_packed_size
                     (const Verteilen2__Job   *message);
size_t verteilen2__job__pack
                     (const Verteilen2__Job   *message,
                      uint8_t             *out);
size_t verteilen2__job__pack_to_buffer
                     (const Verteilen2__Job   *message,
                      ProtobufCBuffer     *buffer);
Verteilen2__Job *
       verteilen2__job__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   verteilen2__job__free_unpacked
                     (Verteilen2__Job *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Verteilen2__Job_Closure)
                 (const Verteilen2__Job *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor verteilen2__job__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_job_2eproto__INCLUDED */
