/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: profile.proto */

#ifndef PROTOBUF_C_profile_2eproto__INCLUDED
#define PROTOBUF_C_profile_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Verteilen2__Profile Verteilen2__Profile;
typedef struct Verteilen2__Profile__MapBooleanEntry Verteilen2__Profile__MapBooleanEntry;
typedef struct Verteilen2__Profile__MapInt32Entry Verteilen2__Profile__MapInt32Entry;
typedef struct Verteilen2__Profile__MapInt64Entry Verteilen2__Profile__MapInt64Entry;
typedef struct Verteilen2__Profile__MapFloatEntry Verteilen2__Profile__MapFloatEntry;
typedef struct Verteilen2__Profile__MapDoubleEntry Verteilen2__Profile__MapDoubleEntry;
typedef struct Verteilen2__Profile__MapStringEntry Verteilen2__Profile__MapStringEntry;


/* --- enums --- */


/* --- messages --- */

struct  Verteilen2__Profile__MapBooleanEntry
{
  ProtobufCMessage base;
  char *key;
  protobuf_c_boolean value;
};
#define VERTEILEN2__PROFILE__MAP_BOOLEAN_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__profile__map_boolean_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Verteilen2__Profile__MapInt32Entry
{
  ProtobufCMessage base;
  char *key;
  int32_t value;
};
#define VERTEILEN2__PROFILE__MAP_INT32_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__profile__map_int32_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Verteilen2__Profile__MapInt64Entry
{
  ProtobufCMessage base;
  char *key;
  int64_t value;
};
#define VERTEILEN2__PROFILE__MAP_INT64_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__profile__map_int64_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Verteilen2__Profile__MapFloatEntry
{
  ProtobufCMessage base;
  char *key;
  float value;
};
#define VERTEILEN2__PROFILE__MAP_FLOAT_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__profile__map_float_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Verteilen2__Profile__MapDoubleEntry
{
  ProtobufCMessage base;
  char *key;
  double value;
};
#define VERTEILEN2__PROFILE__MAP_DOUBLE_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__profile__map_double_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Verteilen2__Profile__MapStringEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define VERTEILEN2__PROFILE__MAP_STRING_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__profile__map_string_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * MsgType: DEBUG_LOG
 */
struct  Verteilen2__Profile
{
  ProtobufCMessage base;
  char *id;
  char *name;
  int32_t type;
  char *script;
  size_t n_map_boolean;
  Verteilen2__Profile__MapBooleanEntry **map_boolean;
  size_t n_map_int32;
  Verteilen2__Profile__MapInt32Entry **map_int32;
  size_t n_map_int64;
  Verteilen2__Profile__MapInt64Entry **map_int64;
  size_t n_map_float;
  Verteilen2__Profile__MapFloatEntry **map_float;
  size_t n_map_double;
  Verteilen2__Profile__MapDoubleEntry **map_double;
  size_t n_map_string;
  Verteilen2__Profile__MapStringEntry **map_string;
  char *inputs_0;
  char *inputs_1;
  char *inputs_2;
  char *inputs_3;
  char *inputs_4;
};
#define VERTEILEN2__PROFILE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__profile__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Verteilen2__Profile__MapBooleanEntry methods */
void   verteilen2__profile__map_boolean_entry__init
                     (Verteilen2__Profile__MapBooleanEntry         *message);
/* Verteilen2__Profile__MapInt32Entry methods */
void   verteilen2__profile__map_int32_entry__init
                     (Verteilen2__Profile__MapInt32Entry         *message);
/* Verteilen2__Profile__MapInt64Entry methods */
void   verteilen2__profile__map_int64_entry__init
                     (Verteilen2__Profile__MapInt64Entry         *message);
/* Verteilen2__Profile__MapFloatEntry methods */
void   verteilen2__profile__map_float_entry__init
                     (Verteilen2__Profile__MapFloatEntry         *message);
/* Verteilen2__Profile__MapDoubleEntry methods */
void   verteilen2__profile__map_double_entry__init
                     (Verteilen2__Profile__MapDoubleEntry         *message);
/* Verteilen2__Profile__MapStringEntry methods */
void   verteilen2__profile__map_string_entry__init
                     (Verteilen2__Profile__MapStringEntry         *message);
/* Verteilen2__Profile methods */
void   verteilen2__profile__init
                     (Verteilen2__Profile         *message);
size_t verteilen2__profile__get_packed_size
                     (const Verteilen2__Profile   *message);
size_t verteilen2__profile__pack
                     (const Verteilen2__Profile   *message,
                      uint8_t             *out);
size_t verteilen2__profile__pack_to_buffer
                     (const Verteilen2__Profile   *message,
                      ProtobufCBuffer     *buffer);
Verteilen2__Profile *
       verteilen2__profile__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   verteilen2__profile__free_unpacked
                     (Verteilen2__Profile *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Verteilen2__Profile__MapBooleanEntry_Closure)
                 (const Verteilen2__Profile__MapBooleanEntry *message,
                  void *closure_data);
typedef void (*Verteilen2__Profile__MapInt32Entry_Closure)
                 (const Verteilen2__Profile__MapInt32Entry *message,
                  void *closure_data);
typedef void (*Verteilen2__Profile__MapInt64Entry_Closure)
                 (const Verteilen2__Profile__MapInt64Entry *message,
                  void *closure_data);
typedef void (*Verteilen2__Profile__MapFloatEntry_Closure)
                 (const Verteilen2__Profile__MapFloatEntry *message,
                  void *closure_data);
typedef void (*Verteilen2__Profile__MapDoubleEntry_Closure)
                 (const Verteilen2__Profile__MapDoubleEntry *message,
                  void *closure_data);
typedef void (*Verteilen2__Profile__MapStringEntry_Closure)
                 (const Verteilen2__Profile__MapStringEntry *message,
                  void *closure_data);
typedef void (*Verteilen2__Profile_Closure)
                 (const Verteilen2__Profile *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor verteilen2__profile__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__profile__map_boolean_entry__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__profile__map_int32_entry__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__profile__map_int64_entry__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__profile__map_float_entry__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__profile__map_double_entry__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__profile__map_string_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_profile_2eproto__INCLUDED */
