// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_profile_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_profile_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_profile_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_profile_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_profile_2eproto;
namespace verteilen2 {
class Profile;
struct ProfileDefaultTypeInternal;
extern ProfileDefaultTypeInternal _Profile_default_instance_;
class Profile_MapBooleanEntry_DoNotUse;
struct Profile_MapBooleanEntry_DoNotUseDefaultTypeInternal;
extern Profile_MapBooleanEntry_DoNotUseDefaultTypeInternal _Profile_MapBooleanEntry_DoNotUse_default_instance_;
class Profile_MapDoubleEntry_DoNotUse;
struct Profile_MapDoubleEntry_DoNotUseDefaultTypeInternal;
extern Profile_MapDoubleEntry_DoNotUseDefaultTypeInternal _Profile_MapDoubleEntry_DoNotUse_default_instance_;
class Profile_MapFloatEntry_DoNotUse;
struct Profile_MapFloatEntry_DoNotUseDefaultTypeInternal;
extern Profile_MapFloatEntry_DoNotUseDefaultTypeInternal _Profile_MapFloatEntry_DoNotUse_default_instance_;
class Profile_MapInt32Entry_DoNotUse;
struct Profile_MapInt32Entry_DoNotUseDefaultTypeInternal;
extern Profile_MapInt32Entry_DoNotUseDefaultTypeInternal _Profile_MapInt32Entry_DoNotUse_default_instance_;
class Profile_MapInt64Entry_DoNotUse;
struct Profile_MapInt64Entry_DoNotUseDefaultTypeInternal;
extern Profile_MapInt64Entry_DoNotUseDefaultTypeInternal _Profile_MapInt64Entry_DoNotUse_default_instance_;
class Profile_MapStringEntry_DoNotUse;
struct Profile_MapStringEntry_DoNotUseDefaultTypeInternal;
extern Profile_MapStringEntry_DoNotUseDefaultTypeInternal _Profile_MapStringEntry_DoNotUse_default_instance_;
}  // namespace verteilen2
PROTOBUF_NAMESPACE_OPEN
template<> ::verteilen2::Profile* Arena::CreateMaybeMessage<::verteilen2::Profile>(Arena*);
template<> ::verteilen2::Profile_MapBooleanEntry_DoNotUse* Arena::CreateMaybeMessage<::verteilen2::Profile_MapBooleanEntry_DoNotUse>(Arena*);
template<> ::verteilen2::Profile_MapDoubleEntry_DoNotUse* Arena::CreateMaybeMessage<::verteilen2::Profile_MapDoubleEntry_DoNotUse>(Arena*);
template<> ::verteilen2::Profile_MapFloatEntry_DoNotUse* Arena::CreateMaybeMessage<::verteilen2::Profile_MapFloatEntry_DoNotUse>(Arena*);
template<> ::verteilen2::Profile_MapInt32Entry_DoNotUse* Arena::CreateMaybeMessage<::verteilen2::Profile_MapInt32Entry_DoNotUse>(Arena*);
template<> ::verteilen2::Profile_MapInt64Entry_DoNotUse* Arena::CreateMaybeMessage<::verteilen2::Profile_MapInt64Entry_DoNotUse>(Arena*);
template<> ::verteilen2::Profile_MapStringEntry_DoNotUse* Arena::CreateMaybeMessage<::verteilen2::Profile_MapStringEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace verteilen2 {

// ===================================================================

class Profile_MapBooleanEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapBooleanEntry_DoNotUse, 
    std::string, bool,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BOOL> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapBooleanEntry_DoNotUse, 
    std::string, bool,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BOOL> SuperType;
  Profile_MapBooleanEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR Profile_MapBooleanEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit Profile_MapBooleanEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Profile_MapBooleanEntry_DoNotUse& other);
  static const Profile_MapBooleanEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Profile_MapBooleanEntry_DoNotUse*>(&_Profile_MapBooleanEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "verteilen2.Profile.MapBooleanEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_profile_2eproto;
};

// -------------------------------------------------------------------

class Profile_MapInt32Entry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapInt32Entry_DoNotUse, 
    std::string, int32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapInt32Entry_DoNotUse, 
    std::string, int32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> SuperType;
  Profile_MapInt32Entry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR Profile_MapInt32Entry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit Profile_MapInt32Entry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Profile_MapInt32Entry_DoNotUse& other);
  static const Profile_MapInt32Entry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Profile_MapInt32Entry_DoNotUse*>(&_Profile_MapInt32Entry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "verteilen2.Profile.MapInt32Entry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_profile_2eproto;
};

// -------------------------------------------------------------------

class Profile_MapInt64Entry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapInt64Entry_DoNotUse, 
    std::string, int64_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapInt64Entry_DoNotUse, 
    std::string, int64_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64> SuperType;
  Profile_MapInt64Entry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR Profile_MapInt64Entry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit Profile_MapInt64Entry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Profile_MapInt64Entry_DoNotUse& other);
  static const Profile_MapInt64Entry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Profile_MapInt64Entry_DoNotUse*>(&_Profile_MapInt64Entry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "verteilen2.Profile.MapInt64Entry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_profile_2eproto;
};

// -------------------------------------------------------------------

class Profile_MapFloatEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapFloatEntry_DoNotUse, 
    std::string, float,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapFloatEntry_DoNotUse, 
    std::string, float,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> SuperType;
  Profile_MapFloatEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR Profile_MapFloatEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit Profile_MapFloatEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Profile_MapFloatEntry_DoNotUse& other);
  static const Profile_MapFloatEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Profile_MapFloatEntry_DoNotUse*>(&_Profile_MapFloatEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "verteilen2.Profile.MapFloatEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_profile_2eproto;
};

// -------------------------------------------------------------------

class Profile_MapDoubleEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapDoubleEntry_DoNotUse, 
    std::string, double,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapDoubleEntry_DoNotUse, 
    std::string, double,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE> SuperType;
  Profile_MapDoubleEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR Profile_MapDoubleEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit Profile_MapDoubleEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Profile_MapDoubleEntry_DoNotUse& other);
  static const Profile_MapDoubleEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Profile_MapDoubleEntry_DoNotUse*>(&_Profile_MapDoubleEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "verteilen2.Profile.MapDoubleEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_profile_2eproto;
};

// -------------------------------------------------------------------

class Profile_MapStringEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapStringEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Profile_MapStringEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  Profile_MapStringEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR Profile_MapStringEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit Profile_MapStringEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Profile_MapStringEntry_DoNotUse& other);
  static const Profile_MapStringEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Profile_MapStringEntry_DoNotUse*>(&_Profile_MapStringEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "verteilen2.Profile.MapStringEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "verteilen2.Profile.MapStringEntry.value");
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_profile_2eproto;
};

// -------------------------------------------------------------------

class Profile final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:verteilen2.Profile) */ {
 public:
  inline Profile() : Profile(nullptr) {}
  ~Profile() override;
  explicit PROTOBUF_CONSTEXPR Profile(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Profile(const Profile& from);
  Profile(Profile&& from) noexcept
    : Profile() {
    *this = ::std::move(from);
  }

  inline Profile& operator=(const Profile& from) {
    CopyFrom(from);
    return *this;
  }
  inline Profile& operator=(Profile&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Profile& default_instance() {
    return *internal_default_instance();
  }
  static inline const Profile* internal_default_instance() {
    return reinterpret_cast<const Profile*>(
               &_Profile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Profile& a, Profile& b) {
    a.Swap(&b);
  }
  inline void Swap(Profile* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Profile* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Profile* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Profile>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Profile& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Profile& from) {
    Profile::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Profile* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "verteilen2.Profile";
  }
  protected:
  explicit Profile(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kMapBooleanFieldNumber = 5,
    kMapInt32FieldNumber = 6,
    kMapInt64FieldNumber = 7,
    kMapFloatFieldNumber = 8,
    kMapDoubleFieldNumber = 9,
    kMapStringFieldNumber = 10,
    kIdFieldNumber = 1,
    kNameFieldNumber = 2,
    kScriptFieldNumber = 4,
    kInputs0FieldNumber = 11,
    kInputs1FieldNumber = 12,
    kInputs2FieldNumber = 13,
    kInputs3FieldNumber = 14,
    kInputs4FieldNumber = 15,
    kTypeFieldNumber = 3,
  };
  // map<string, bool> map_boolean = 5;
  int map_boolean_size() const;
  private:
  int _internal_map_boolean_size() const;
  public:
  void clear_map_boolean();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >&
      _internal_map_boolean() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >*
      _internal_mutable_map_boolean();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >&
      map_boolean() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >*
      mutable_map_boolean();

  // map<string, int32> map_int32 = 6;
  int map_int32_size() const;
  private:
  int _internal_map_int32_size() const;
  public:
  void clear_map_int32();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
      _internal_map_int32() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
      _internal_mutable_map_int32();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
      map_int32() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
      mutable_map_int32();

  // map<string, int64> map_int64 = 7;
  int map_int64_size() const;
  private:
  int _internal_map_int64_size() const;
  public:
  void clear_map_int64();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int64_t >&
      _internal_map_int64() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, int64_t >*
      _internal_mutable_map_int64();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int64_t >&
      map_int64() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, int64_t >*
      mutable_map_int64();

  // map<string, float> map_float = 8;
  int map_float_size() const;
  private:
  int _internal_map_float_size() const;
  public:
  void clear_map_float();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
      _internal_map_float() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
      _internal_mutable_map_float();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
      map_float() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
      mutable_map_float();

  // map<string, double> map_double = 9;
  int map_double_size() const;
  private:
  int _internal_map_double_size() const;
  public:
  void clear_map_double();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >&
      _internal_map_double() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >*
      _internal_mutable_map_double();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >&
      map_double() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >*
      mutable_map_double();

  // map<string, string> map_string = 10;
  int map_string_size() const;
  private:
  int _internal_map_string_size() const;
  public:
  void clear_map_string();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_map_string() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_map_string();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      map_string() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_map_string();

  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string script = 4;
  void clear_script();
  const std::string& script() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_script(ArgT0&& arg0, ArgT... args);
  std::string* mutable_script();
  PROTOBUF_NODISCARD std::string* release_script();
  void set_allocated_script(std::string* script);
  private:
  const std::string& _internal_script() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_script(const std::string& value);
  std::string* _internal_mutable_script();
  public:

  // string inputs_0 = 11;
  void clear_inputs_0();
  const std::string& inputs_0() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inputs_0(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inputs_0();
  PROTOBUF_NODISCARD std::string* release_inputs_0();
  void set_allocated_inputs_0(std::string* inputs_0);
  private:
  const std::string& _internal_inputs_0() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inputs_0(const std::string& value);
  std::string* _internal_mutable_inputs_0();
  public:

  // string inputs_1 = 12;
  void clear_inputs_1();
  const std::string& inputs_1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inputs_1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inputs_1();
  PROTOBUF_NODISCARD std::string* release_inputs_1();
  void set_allocated_inputs_1(std::string* inputs_1);
  private:
  const std::string& _internal_inputs_1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inputs_1(const std::string& value);
  std::string* _internal_mutable_inputs_1();
  public:

  // string inputs_2 = 13;
  void clear_inputs_2();
  const std::string& inputs_2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inputs_2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inputs_2();
  PROTOBUF_NODISCARD std::string* release_inputs_2();
  void set_allocated_inputs_2(std::string* inputs_2);
  private:
  const std::string& _internal_inputs_2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inputs_2(const std::string& value);
  std::string* _internal_mutable_inputs_2();
  public:

  // string inputs_3 = 14;
  void clear_inputs_3();
  const std::string& inputs_3() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inputs_3(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inputs_3();
  PROTOBUF_NODISCARD std::string* release_inputs_3();
  void set_allocated_inputs_3(std::string* inputs_3);
  private:
  const std::string& _internal_inputs_3() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inputs_3(const std::string& value);
  std::string* _internal_mutable_inputs_3();
  public:

  // string inputs_4 = 15;
  void clear_inputs_4();
  const std::string& inputs_4() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inputs_4(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inputs_4();
  PROTOBUF_NODISCARD std::string* release_inputs_4();
  void set_allocated_inputs_4(std::string* inputs_4);
  private:
  const std::string& _internal_inputs_4() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inputs_4(const std::string& value);
  std::string* _internal_mutable_inputs_4();
  public:

  // int32 type = 3;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:verteilen2.Profile)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        Profile_MapBooleanEntry_DoNotUse,
        std::string, bool,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BOOL> map_boolean_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        Profile_MapInt32Entry_DoNotUse,
        std::string, int32_t,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> map_int32_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        Profile_MapInt64Entry_DoNotUse,
        std::string, int64_t,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64> map_int64_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        Profile_MapFloatEntry_DoNotUse,
        std::string, float,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> map_float_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        Profile_MapDoubleEntry_DoNotUse,
        std::string, double,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE> map_double_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        Profile_MapStringEntry_DoNotUse,
        std::string, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> map_string_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr script_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputs_0_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputs_1_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputs_2_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputs_3_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputs_4_;
    int32_t type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_profile_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Profile

// string id = 1;
inline void Profile::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& Profile::id() const {
  // @@protoc_insertion_point(field_get:verteilen2.Profile.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Profile::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Profile.id)
}
inline std::string* Profile::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:verteilen2.Profile.id)
  return _s;
}
inline const std::string& Profile::_internal_id() const {
  return _impl_.id_.Get();
}
inline void Profile::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* Profile::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* Profile::release_id() {
  // @@protoc_insertion_point(field_release:verteilen2.Profile.id)
  return _impl_.id_.Release();
}
inline void Profile::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Profile.id)
}

// string name = 2;
inline void Profile::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Profile::name() const {
  // @@protoc_insertion_point(field_get:verteilen2.Profile.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Profile::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Profile.name)
}
inline std::string* Profile::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:verteilen2.Profile.name)
  return _s;
}
inline const std::string& Profile::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Profile::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Profile::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Profile::release_name() {
  // @@protoc_insertion_point(field_release:verteilen2.Profile.name)
  return _impl_.name_.Release();
}
inline void Profile::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Profile.name)
}

// int32 type = 3;
inline void Profile::clear_type() {
  _impl_.type_ = 0;
}
inline int32_t Profile::_internal_type() const {
  return _impl_.type_;
}
inline int32_t Profile::type() const {
  // @@protoc_insertion_point(field_get:verteilen2.Profile.type)
  return _internal_type();
}
inline void Profile::_internal_set_type(int32_t value) {
  
  _impl_.type_ = value;
}
inline void Profile::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:verteilen2.Profile.type)
}

// string script = 4;
inline void Profile::clear_script() {
  _impl_.script_.ClearToEmpty();
}
inline const std::string& Profile::script() const {
  // @@protoc_insertion_point(field_get:verteilen2.Profile.script)
  return _internal_script();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Profile::set_script(ArgT0&& arg0, ArgT... args) {
 
 _impl_.script_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Profile.script)
}
inline std::string* Profile::mutable_script() {
  std::string* _s = _internal_mutable_script();
  // @@protoc_insertion_point(field_mutable:verteilen2.Profile.script)
  return _s;
}
inline const std::string& Profile::_internal_script() const {
  return _impl_.script_.Get();
}
inline void Profile::_internal_set_script(const std::string& value) {
  
  _impl_.script_.Set(value, GetArenaForAllocation());
}
inline std::string* Profile::_internal_mutable_script() {
  
  return _impl_.script_.Mutable(GetArenaForAllocation());
}
inline std::string* Profile::release_script() {
  // @@protoc_insertion_point(field_release:verteilen2.Profile.script)
  return _impl_.script_.Release();
}
inline void Profile::set_allocated_script(std::string* script) {
  if (script != nullptr) {
    
  } else {
    
  }
  _impl_.script_.SetAllocated(script, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.script_.IsDefault()) {
    _impl_.script_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Profile.script)
}

// map<string, bool> map_boolean = 5;
inline int Profile::_internal_map_boolean_size() const {
  return _impl_.map_boolean_.size();
}
inline int Profile::map_boolean_size() const {
  return _internal_map_boolean_size();
}
inline void Profile::clear_map_boolean() {
  _impl_.map_boolean_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >&
Profile::_internal_map_boolean() const {
  return _impl_.map_boolean_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >&
Profile::map_boolean() const {
  // @@protoc_insertion_point(field_map:verteilen2.Profile.map_boolean)
  return _internal_map_boolean();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >*
Profile::_internal_mutable_map_boolean() {
  return _impl_.map_boolean_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >*
Profile::mutable_map_boolean() {
  // @@protoc_insertion_point(field_mutable_map:verteilen2.Profile.map_boolean)
  return _internal_mutable_map_boolean();
}

// map<string, int32> map_int32 = 6;
inline int Profile::_internal_map_int32_size() const {
  return _impl_.map_int32_.size();
}
inline int Profile::map_int32_size() const {
  return _internal_map_int32_size();
}
inline void Profile::clear_map_int32() {
  _impl_.map_int32_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
Profile::_internal_map_int32() const {
  return _impl_.map_int32_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
Profile::map_int32() const {
  // @@protoc_insertion_point(field_map:verteilen2.Profile.map_int32)
  return _internal_map_int32();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
Profile::_internal_mutable_map_int32() {
  return _impl_.map_int32_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
Profile::mutable_map_int32() {
  // @@protoc_insertion_point(field_mutable_map:verteilen2.Profile.map_int32)
  return _internal_mutable_map_int32();
}

// map<string, int64> map_int64 = 7;
inline int Profile::_internal_map_int64_size() const {
  return _impl_.map_int64_.size();
}
inline int Profile::map_int64_size() const {
  return _internal_map_int64_size();
}
inline void Profile::clear_map_int64() {
  _impl_.map_int64_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int64_t >&
Profile::_internal_map_int64() const {
  return _impl_.map_int64_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int64_t >&
Profile::map_int64() const {
  // @@protoc_insertion_point(field_map:verteilen2.Profile.map_int64)
  return _internal_map_int64();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, int64_t >*
Profile::_internal_mutable_map_int64() {
  return _impl_.map_int64_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, int64_t >*
Profile::mutable_map_int64() {
  // @@protoc_insertion_point(field_mutable_map:verteilen2.Profile.map_int64)
  return _internal_mutable_map_int64();
}

// map<string, float> map_float = 8;
inline int Profile::_internal_map_float_size() const {
  return _impl_.map_float_.size();
}
inline int Profile::map_float_size() const {
  return _internal_map_float_size();
}
inline void Profile::clear_map_float() {
  _impl_.map_float_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
Profile::_internal_map_float() const {
  return _impl_.map_float_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
Profile::map_float() const {
  // @@protoc_insertion_point(field_map:verteilen2.Profile.map_float)
  return _internal_map_float();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
Profile::_internal_mutable_map_float() {
  return _impl_.map_float_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
Profile::mutable_map_float() {
  // @@protoc_insertion_point(field_mutable_map:verteilen2.Profile.map_float)
  return _internal_mutable_map_float();
}

// map<string, double> map_double = 9;
inline int Profile::_internal_map_double_size() const {
  return _impl_.map_double_.size();
}
inline int Profile::map_double_size() const {
  return _internal_map_double_size();
}
inline void Profile::clear_map_double() {
  _impl_.map_double_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >&
Profile::_internal_map_double() const {
  return _impl_.map_double_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >&
Profile::map_double() const {
  // @@protoc_insertion_point(field_map:verteilen2.Profile.map_double)
  return _internal_map_double();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >*
Profile::_internal_mutable_map_double() {
  return _impl_.map_double_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >*
Profile::mutable_map_double() {
  // @@protoc_insertion_point(field_mutable_map:verteilen2.Profile.map_double)
  return _internal_mutable_map_double();
}

// map<string, string> map_string = 10;
inline int Profile::_internal_map_string_size() const {
  return _impl_.map_string_.size();
}
inline int Profile::map_string_size() const {
  return _internal_map_string_size();
}
inline void Profile::clear_map_string() {
  _impl_.map_string_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
Profile::_internal_map_string() const {
  return _impl_.map_string_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
Profile::map_string() const {
  // @@protoc_insertion_point(field_map:verteilen2.Profile.map_string)
  return _internal_map_string();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
Profile::_internal_mutable_map_string() {
  return _impl_.map_string_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
Profile::mutable_map_string() {
  // @@protoc_insertion_point(field_mutable_map:verteilen2.Profile.map_string)
  return _internal_mutable_map_string();
}

// string inputs_0 = 11;
inline void Profile::clear_inputs_0() {
  _impl_.inputs_0_.ClearToEmpty();
}
inline const std::string& Profile::inputs_0() const {
  // @@protoc_insertion_point(field_get:verteilen2.Profile.inputs_0)
  return _internal_inputs_0();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Profile::set_inputs_0(ArgT0&& arg0, ArgT... args) {
 
 _impl_.inputs_0_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Profile.inputs_0)
}
inline std::string* Profile::mutable_inputs_0() {
  std::string* _s = _internal_mutable_inputs_0();
  // @@protoc_insertion_point(field_mutable:verteilen2.Profile.inputs_0)
  return _s;
}
inline const std::string& Profile::_internal_inputs_0() const {
  return _impl_.inputs_0_.Get();
}
inline void Profile::_internal_set_inputs_0(const std::string& value) {
  
  _impl_.inputs_0_.Set(value, GetArenaForAllocation());
}
inline std::string* Profile::_internal_mutable_inputs_0() {
  
  return _impl_.inputs_0_.Mutable(GetArenaForAllocation());
}
inline std::string* Profile::release_inputs_0() {
  // @@protoc_insertion_point(field_release:verteilen2.Profile.inputs_0)
  return _impl_.inputs_0_.Release();
}
inline void Profile::set_allocated_inputs_0(std::string* inputs_0) {
  if (inputs_0 != nullptr) {
    
  } else {
    
  }
  _impl_.inputs_0_.SetAllocated(inputs_0, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inputs_0_.IsDefault()) {
    _impl_.inputs_0_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Profile.inputs_0)
}

// string inputs_1 = 12;
inline void Profile::clear_inputs_1() {
  _impl_.inputs_1_.ClearToEmpty();
}
inline const std::string& Profile::inputs_1() const {
  // @@protoc_insertion_point(field_get:verteilen2.Profile.inputs_1)
  return _internal_inputs_1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Profile::set_inputs_1(ArgT0&& arg0, ArgT... args) {
 
 _impl_.inputs_1_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Profile.inputs_1)
}
inline std::string* Profile::mutable_inputs_1() {
  std::string* _s = _internal_mutable_inputs_1();
  // @@protoc_insertion_point(field_mutable:verteilen2.Profile.inputs_1)
  return _s;
}
inline const std::string& Profile::_internal_inputs_1() const {
  return _impl_.inputs_1_.Get();
}
inline void Profile::_internal_set_inputs_1(const std::string& value) {
  
  _impl_.inputs_1_.Set(value, GetArenaForAllocation());
}
inline std::string* Profile::_internal_mutable_inputs_1() {
  
  return _impl_.inputs_1_.Mutable(GetArenaForAllocation());
}
inline std::string* Profile::release_inputs_1() {
  // @@protoc_insertion_point(field_release:verteilen2.Profile.inputs_1)
  return _impl_.inputs_1_.Release();
}
inline void Profile::set_allocated_inputs_1(std::string* inputs_1) {
  if (inputs_1 != nullptr) {
    
  } else {
    
  }
  _impl_.inputs_1_.SetAllocated(inputs_1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inputs_1_.IsDefault()) {
    _impl_.inputs_1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Profile.inputs_1)
}

// string inputs_2 = 13;
inline void Profile::clear_inputs_2() {
  _impl_.inputs_2_.ClearToEmpty();
}
inline const std::string& Profile::inputs_2() const {
  // @@protoc_insertion_point(field_get:verteilen2.Profile.inputs_2)
  return _internal_inputs_2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Profile::set_inputs_2(ArgT0&& arg0, ArgT... args) {
 
 _impl_.inputs_2_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Profile.inputs_2)
}
inline std::string* Profile::mutable_inputs_2() {
  std::string* _s = _internal_mutable_inputs_2();
  // @@protoc_insertion_point(field_mutable:verteilen2.Profile.inputs_2)
  return _s;
}
inline const std::string& Profile::_internal_inputs_2() const {
  return _impl_.inputs_2_.Get();
}
inline void Profile::_internal_set_inputs_2(const std::string& value) {
  
  _impl_.inputs_2_.Set(value, GetArenaForAllocation());
}
inline std::string* Profile::_internal_mutable_inputs_2() {
  
  return _impl_.inputs_2_.Mutable(GetArenaForAllocation());
}
inline std::string* Profile::release_inputs_2() {
  // @@protoc_insertion_point(field_release:verteilen2.Profile.inputs_2)
  return _impl_.inputs_2_.Release();
}
inline void Profile::set_allocated_inputs_2(std::string* inputs_2) {
  if (inputs_2 != nullptr) {
    
  } else {
    
  }
  _impl_.inputs_2_.SetAllocated(inputs_2, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inputs_2_.IsDefault()) {
    _impl_.inputs_2_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Profile.inputs_2)
}

// string inputs_3 = 14;
inline void Profile::clear_inputs_3() {
  _impl_.inputs_3_.ClearToEmpty();
}
inline const std::string& Profile::inputs_3() const {
  // @@protoc_insertion_point(field_get:verteilen2.Profile.inputs_3)
  return _internal_inputs_3();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Profile::set_inputs_3(ArgT0&& arg0, ArgT... args) {
 
 _impl_.inputs_3_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Profile.inputs_3)
}
inline std::string* Profile::mutable_inputs_3() {
  std::string* _s = _internal_mutable_inputs_3();
  // @@protoc_insertion_point(field_mutable:verteilen2.Profile.inputs_3)
  return _s;
}
inline const std::string& Profile::_internal_inputs_3() const {
  return _impl_.inputs_3_.Get();
}
inline void Profile::_internal_set_inputs_3(const std::string& value) {
  
  _impl_.inputs_3_.Set(value, GetArenaForAllocation());
}
inline std::string* Profile::_internal_mutable_inputs_3() {
  
  return _impl_.inputs_3_.Mutable(GetArenaForAllocation());
}
inline std::string* Profile::release_inputs_3() {
  // @@protoc_insertion_point(field_release:verteilen2.Profile.inputs_3)
  return _impl_.inputs_3_.Release();
}
inline void Profile::set_allocated_inputs_3(std::string* inputs_3) {
  if (inputs_3 != nullptr) {
    
  } else {
    
  }
  _impl_.inputs_3_.SetAllocated(inputs_3, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inputs_3_.IsDefault()) {
    _impl_.inputs_3_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Profile.inputs_3)
}

// string inputs_4 = 15;
inline void Profile::clear_inputs_4() {
  _impl_.inputs_4_.ClearToEmpty();
}
inline const std::string& Profile::inputs_4() const {
  // @@protoc_insertion_point(field_get:verteilen2.Profile.inputs_4)
  return _internal_inputs_4();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Profile::set_inputs_4(ArgT0&& arg0, ArgT... args) {
 
 _impl_.inputs_4_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Profile.inputs_4)
}
inline std::string* Profile::mutable_inputs_4() {
  std::string* _s = _internal_mutable_inputs_4();
  // @@protoc_insertion_point(field_mutable:verteilen2.Profile.inputs_4)
  return _s;
}
inline const std::string& Profile::_internal_inputs_4() const {
  return _impl_.inputs_4_.Get();
}
inline void Profile::_internal_set_inputs_4(const std::string& value) {
  
  _impl_.inputs_4_.Set(value, GetArenaForAllocation());
}
inline std::string* Profile::_internal_mutable_inputs_4() {
  
  return _impl_.inputs_4_.Mutable(GetArenaForAllocation());
}
inline std::string* Profile::release_inputs_4() {
  // @@protoc_insertion_point(field_release:verteilen2.Profile.inputs_4)
  return _impl_.inputs_4_.Release();
}
inline void Profile::set_allocated_inputs_4(std::string* inputs_4) {
  if (inputs_4 != nullptr) {
    
  } else {
    
  }
  _impl_.inputs_4_.SetAllocated(inputs_4, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inputs_4_.IsDefault()) {
    _impl_.inputs_4_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Profile.inputs_4)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace verteilen2

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_profile_2eproto
