/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: project.proto */

#ifndef PROTOBUF_C_project_2eproto__INCLUDED
#define PROTOBUF_C_project_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "data_field.pb-c.h"

typedef struct Verteilen2__Project Verteilen2__Project;


/* --- enums --- */


/* --- messages --- */

struct  Verteilen2__Project
{
  ProtobufCMessage base;
  char *uuid;
  char *name;
  char *description;
  Verteilen2__DataField *vault;
  size_t n_tasks;
  Verteilen2__DataField **tasks;
};
#define VERTEILEN2__PROJECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__project__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, NULL, 0,NULL }


/* Verteilen2__Project methods */
void   verteilen2__project__init
                     (Verteilen2__Project         *message);
size_t verteilen2__project__get_packed_size
                     (const Verteilen2__Project   *message);
size_t verteilen2__project__pack
                     (const Verteilen2__Project   *message,
                      uint8_t             *out);
size_t verteilen2__project__pack_to_buffer
                     (const Verteilen2__Project   *message,
                      ProtobufCBuffer     *buffer);
Verteilen2__Project *
       verteilen2__project__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   verteilen2__project__free_unpacked
                     (Verteilen2__Project *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Verteilen2__Project_Closure)
                 (const Verteilen2__Project *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor verteilen2__project__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_project_2eproto__INCLUDED */
