/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: task.proto */

#ifndef PROTOBUF_C_task_2eproto__INCLUDED
#define PROTOBUF_C_task_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "data_field.pb-c.h"

typedef struct Verteilen2__Task Verteilen2__Task;


/* --- enums --- */


/* --- messages --- */

struct  Verteilen2__Task
{
  ProtobufCMessage base;
  char *uuid;
  char *name;
  char *description;
  int32_t type;
  char *cluster_field_key;
  char *multicore_field_key;
  size_t n_jobs;
  Verteilen2__DataField **jobs;
};
#define VERTEILEN2__TASK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__task__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


/* Verteilen2__Task methods */
void   verteilen2__task__init
                     (Verteilen2__Task         *message);
size_t verteilen2__task__get_packed_size
                     (const Verteilen2__Task   *message);
size_t verteilen2__task__pack
                     (const Verteilen2__Task   *message,
                      uint8_t             *out);
size_t verteilen2__task__pack_to_buffer
                     (const Verteilen2__Task   *message,
                      ProtobufCBuffer     *buffer);
Verteilen2__Task *
       verteilen2__task__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   verteilen2__task__free_unpacked
                     (Verteilen2__Task *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Verteilen2__Task_Closure)
                 (const Verteilen2__Task *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor verteilen2__task__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_task_2eproto__INCLUDED */
