// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_task_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_task_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "data_field.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_task_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_task_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_task_2eproto;
namespace verteilen2 {
class Task;
struct TaskDefaultTypeInternal;
extern TaskDefaultTypeInternal _Task_default_instance_;
}  // namespace verteilen2
PROTOBUF_NAMESPACE_OPEN
template<> ::verteilen2::Task* Arena::CreateMaybeMessage<::verteilen2::Task>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace verteilen2 {

// ===================================================================

class Task final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:verteilen2.Task) */ {
 public:
  inline Task() : Task(nullptr) {}
  ~Task() override;
  explicit PROTOBUF_CONSTEXPR Task(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Task(const Task& from);
  Task(Task&& from) noexcept
    : Task() {
    *this = ::std::move(from);
  }

  inline Task& operator=(const Task& from) {
    CopyFrom(from);
    return *this;
  }
  inline Task& operator=(Task&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Task& default_instance() {
    return *internal_default_instance();
  }
  static inline const Task* internal_default_instance() {
    return reinterpret_cast<const Task*>(
               &_Task_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Task& a, Task& b) {
    a.Swap(&b);
  }
  inline void Swap(Task* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Task* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Task* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Task>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Task& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Task& from) {
    Task::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Task* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "verteilen2.Task";
  }
  protected:
  explicit Task(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJobsFieldNumber = 7,
    kUuidFieldNumber = 1,
    kNameFieldNumber = 2,
    kDescriptionFieldNumber = 3,
    kClusterFieldKeyFieldNumber = 5,
    kMulticoreFieldKeyFieldNumber = 6,
    kTypeFieldNumber = 4,
  };
  // repeated .verteilen2.DataField jobs = 7;
  int jobs_size() const;
  private:
  int _internal_jobs_size() const;
  public:
  void clear_jobs();
  ::verteilen2::DataField* mutable_jobs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::verteilen2::DataField >*
      mutable_jobs();
  private:
  const ::verteilen2::DataField& _internal_jobs(int index) const;
  ::verteilen2::DataField* _internal_add_jobs();
  public:
  const ::verteilen2::DataField& jobs(int index) const;
  ::verteilen2::DataField* add_jobs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::verteilen2::DataField >&
      jobs() const;

  // string uuid = 1;
  void clear_uuid();
  const std::string& uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string description = 3;
  void clear_description();
  const std::string& description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_description();
  PROTOBUF_NODISCARD std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // string cluster_field_key = 5;
  void clear_cluster_field_key();
  const std::string& cluster_field_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cluster_field_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cluster_field_key();
  PROTOBUF_NODISCARD std::string* release_cluster_field_key();
  void set_allocated_cluster_field_key(std::string* cluster_field_key);
  private:
  const std::string& _internal_cluster_field_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cluster_field_key(const std::string& value);
  std::string* _internal_mutable_cluster_field_key();
  public:

  // string multicore_field_key = 6;
  void clear_multicore_field_key();
  const std::string& multicore_field_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_multicore_field_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_multicore_field_key();
  PROTOBUF_NODISCARD std::string* release_multicore_field_key();
  void set_allocated_multicore_field_key(std::string* multicore_field_key);
  private:
  const std::string& _internal_multicore_field_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_multicore_field_key(const std::string& value);
  std::string* _internal_mutable_multicore_field_key();
  public:

  // int32 type = 4;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:verteilen2.Task)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::verteilen2::DataField > jobs_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cluster_field_key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr multicore_field_key_;
    int32_t type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_task_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Task

// string uuid = 1;
inline void Task::clear_uuid() {
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& Task::uuid() const {
  // @@protoc_insertion_point(field_get:verteilen2.Task.uuid)
  return _internal_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Task::set_uuid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.uuid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Task.uuid)
}
inline std::string* Task::mutable_uuid() {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:verteilen2.Task.uuid)
  return _s;
}
inline const std::string& Task::_internal_uuid() const {
  return _impl_.uuid_.Get();
}
inline void Task::_internal_set_uuid(const std::string& value) {
  
  _impl_.uuid_.Set(value, GetArenaForAllocation());
}
inline std::string* Task::_internal_mutable_uuid() {
  
  return _impl_.uuid_.Mutable(GetArenaForAllocation());
}
inline std::string* Task::release_uuid() {
  // @@protoc_insertion_point(field_release:verteilen2.Task.uuid)
  return _impl_.uuid_.Release();
}
inline void Task::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  _impl_.uuid_.SetAllocated(uuid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Task.uuid)
}

// string name = 2;
inline void Task::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Task::name() const {
  // @@protoc_insertion_point(field_get:verteilen2.Task.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Task::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Task.name)
}
inline std::string* Task::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:verteilen2.Task.name)
  return _s;
}
inline const std::string& Task::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Task::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Task::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Task::release_name() {
  // @@protoc_insertion_point(field_release:verteilen2.Task.name)
  return _impl_.name_.Release();
}
inline void Task::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Task.name)
}

// string description = 3;
inline void Task::clear_description() {
  _impl_.description_.ClearToEmpty();
}
inline const std::string& Task::description() const {
  // @@protoc_insertion_point(field_get:verteilen2.Task.description)
  return _internal_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Task::set_description(ArgT0&& arg0, ArgT... args) {
 
 _impl_.description_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Task.description)
}
inline std::string* Task::mutable_description() {
  std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:verteilen2.Task.description)
  return _s;
}
inline const std::string& Task::_internal_description() const {
  return _impl_.description_.Get();
}
inline void Task::_internal_set_description(const std::string& value) {
  
  _impl_.description_.Set(value, GetArenaForAllocation());
}
inline std::string* Task::_internal_mutable_description() {
  
  return _impl_.description_.Mutable(GetArenaForAllocation());
}
inline std::string* Task::release_description() {
  // @@protoc_insertion_point(field_release:verteilen2.Task.description)
  return _impl_.description_.Release();
}
inline void Task::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  _impl_.description_.SetAllocated(description, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.description_.IsDefault()) {
    _impl_.description_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Task.description)
}

// int32 type = 4;
inline void Task::clear_type() {
  _impl_.type_ = 0;
}
inline int32_t Task::_internal_type() const {
  return _impl_.type_;
}
inline int32_t Task::type() const {
  // @@protoc_insertion_point(field_get:verteilen2.Task.type)
  return _internal_type();
}
inline void Task::_internal_set_type(int32_t value) {
  
  _impl_.type_ = value;
}
inline void Task::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:verteilen2.Task.type)
}

// string cluster_field_key = 5;
inline void Task::clear_cluster_field_key() {
  _impl_.cluster_field_key_.ClearToEmpty();
}
inline const std::string& Task::cluster_field_key() const {
  // @@protoc_insertion_point(field_get:verteilen2.Task.cluster_field_key)
  return _internal_cluster_field_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Task::set_cluster_field_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.cluster_field_key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Task.cluster_field_key)
}
inline std::string* Task::mutable_cluster_field_key() {
  std::string* _s = _internal_mutable_cluster_field_key();
  // @@protoc_insertion_point(field_mutable:verteilen2.Task.cluster_field_key)
  return _s;
}
inline const std::string& Task::_internal_cluster_field_key() const {
  return _impl_.cluster_field_key_.Get();
}
inline void Task::_internal_set_cluster_field_key(const std::string& value) {
  
  _impl_.cluster_field_key_.Set(value, GetArenaForAllocation());
}
inline std::string* Task::_internal_mutable_cluster_field_key() {
  
  return _impl_.cluster_field_key_.Mutable(GetArenaForAllocation());
}
inline std::string* Task::release_cluster_field_key() {
  // @@protoc_insertion_point(field_release:verteilen2.Task.cluster_field_key)
  return _impl_.cluster_field_key_.Release();
}
inline void Task::set_allocated_cluster_field_key(std::string* cluster_field_key) {
  if (cluster_field_key != nullptr) {
    
  } else {
    
  }
  _impl_.cluster_field_key_.SetAllocated(cluster_field_key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.cluster_field_key_.IsDefault()) {
    _impl_.cluster_field_key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Task.cluster_field_key)
}

// string multicore_field_key = 6;
inline void Task::clear_multicore_field_key() {
  _impl_.multicore_field_key_.ClearToEmpty();
}
inline const std::string& Task::multicore_field_key() const {
  // @@protoc_insertion_point(field_get:verteilen2.Task.multicore_field_key)
  return _internal_multicore_field_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Task::set_multicore_field_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.multicore_field_key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Task.multicore_field_key)
}
inline std::string* Task::mutable_multicore_field_key() {
  std::string* _s = _internal_mutable_multicore_field_key();
  // @@protoc_insertion_point(field_mutable:verteilen2.Task.multicore_field_key)
  return _s;
}
inline const std::string& Task::_internal_multicore_field_key() const {
  return _impl_.multicore_field_key_.Get();
}
inline void Task::_internal_set_multicore_field_key(const std::string& value) {
  
  _impl_.multicore_field_key_.Set(value, GetArenaForAllocation());
}
inline std::string* Task::_internal_mutable_multicore_field_key() {
  
  return _impl_.multicore_field_key_.Mutable(GetArenaForAllocation());
}
inline std::string* Task::release_multicore_field_key() {
  // @@protoc_insertion_point(field_release:verteilen2.Task.multicore_field_key)
  return _impl_.multicore_field_key_.Release();
}
inline void Task::set_allocated_multicore_field_key(std::string* multicore_field_key) {
  if (multicore_field_key != nullptr) {
    
  } else {
    
  }
  _impl_.multicore_field_key_.SetAllocated(multicore_field_key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.multicore_field_key_.IsDefault()) {
    _impl_.multicore_field_key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Task.multicore_field_key)
}

// repeated .verteilen2.DataField jobs = 7;
inline int Task::_internal_jobs_size() const {
  return _impl_.jobs_.size();
}
inline int Task::jobs_size() const {
  return _internal_jobs_size();
}
inline ::verteilen2::DataField* Task::mutable_jobs(int index) {
  // @@protoc_insertion_point(field_mutable:verteilen2.Task.jobs)
  return _impl_.jobs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::verteilen2::DataField >*
Task::mutable_jobs() {
  // @@protoc_insertion_point(field_mutable_list:verteilen2.Task.jobs)
  return &_impl_.jobs_;
}
inline const ::verteilen2::DataField& Task::_internal_jobs(int index) const {
  return _impl_.jobs_.Get(index);
}
inline const ::verteilen2::DataField& Task::jobs(int index) const {
  // @@protoc_insertion_point(field_get:verteilen2.Task.jobs)
  return _internal_jobs(index);
}
inline ::verteilen2::DataField* Task::_internal_add_jobs() {
  return _impl_.jobs_.Add();
}
inline ::verteilen2::DataField* Task::add_jobs() {
  ::verteilen2::DataField* _add = _internal_add_jobs();
  // @@protoc_insertion_point(field_add:verteilen2.Task.jobs)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::verteilen2::DataField >&
Task::jobs() const {
  // @@protoc_insertion_point(field_list:verteilen2.Task.jobs)
  return _impl_.jobs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace verteilen2

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_task_2eproto
