/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vault.proto */

#ifndef PROTOBUF_C_vault_2eproto__INCLUDED
#define PROTOBUF_C_vault_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "dynamic_map.pb-c.h"

typedef struct Verteilen2__Vault Verteilen2__Vault;


/* --- enums --- */


/* --- messages --- */

struct  Verteilen2__Vault
{
  ProtobufCMessage base;
  char *uuid;
  char *name;
  char *description;
  Verteilen2__DynamicMap *d_map;
};
#define VERTEILEN2__VAULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__vault__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, NULL }


/* Verteilen2__Vault methods */
void   verteilen2__vault__init
                     (Verteilen2__Vault         *message);
size_t verteilen2__vault__get_packed_size
                     (const Verteilen2__Vault   *message);
size_t verteilen2__vault__pack
                     (const Verteilen2__Vault   *message,
                      uint8_t             *out);
size_t verteilen2__vault__pack_to_buffer
                     (const Verteilen2__Vault   *message,
                      ProtobufCBuffer     *buffer);
Verteilen2__Vault *
       verteilen2__vault__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   verteilen2__vault__free_unpacked
                     (Verteilen2__Vault *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Verteilen2__Vault_Closure)
                 (const Verteilen2__Vault *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor verteilen2__vault__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_vault_2eproto__INCLUDED */
