/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vault.proto */

#ifndef PROTOBUF_C_vault_2eproto__INCLUDED
#define PROTOBUF_C_vault_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Verteilen2__Vault Verteilen2__Vault;
typedef struct Verteilen2__Vault__DataBoolEntry Verteilen2__Vault__DataBoolEntry;
typedef struct Verteilen2__Vault__DataInt32Entry Verteilen2__Vault__DataInt32Entry;
typedef struct Verteilen2__Vault__DataInt64Entry Verteilen2__Vault__DataInt64Entry;
typedef struct Verteilen2__Vault__DataFloatEntry Verteilen2__Vault__DataFloatEntry;
typedef struct Verteilen2__Vault__DataDoubleEntry Verteilen2__Vault__DataDoubleEntry;
typedef struct Verteilen2__Vault__DataStringEntry Verteilen2__Vault__DataStringEntry;


/* --- enums --- */


/* --- messages --- */

struct  Verteilen2__Vault__DataBoolEntry
{
  ProtobufCMessage base;
  char *key;
  protobuf_c_boolean value;
};
#define VERTEILEN2__VAULT__DATA_BOOL_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__vault__data_bool_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Verteilen2__Vault__DataInt32Entry
{
  ProtobufCMessage base;
  char *key;
  int32_t value;
};
#define VERTEILEN2__VAULT__DATA_INT32_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__vault__data_int32_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Verteilen2__Vault__DataInt64Entry
{
  ProtobufCMessage base;
  char *key;
  int64_t value;
};
#define VERTEILEN2__VAULT__DATA_INT64_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__vault__data_int64_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Verteilen2__Vault__DataFloatEntry
{
  ProtobufCMessage base;
  char *key;
  float value;
};
#define VERTEILEN2__VAULT__DATA_FLOAT_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__vault__data_float_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Verteilen2__Vault__DataDoubleEntry
{
  ProtobufCMessage base;
  char *key;
  double value;
};
#define VERTEILEN2__VAULT__DATA_DOUBLE_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__vault__data_double_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Verteilen2__Vault__DataStringEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define VERTEILEN2__VAULT__DATA_STRING_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__vault__data_string_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Verteilen2__Vault
{
  ProtobufCMessage base;
  char *uuid;
  char *name;
  size_t n_data_bool;
  Verteilen2__Vault__DataBoolEntry **data_bool;
  size_t n_data_int32;
  Verteilen2__Vault__DataInt32Entry **data_int32;
  size_t n_data_int64;
  Verteilen2__Vault__DataInt64Entry **data_int64;
  size_t n_data_float;
  Verteilen2__Vault__DataFloatEntry **data_float;
  size_t n_data_double;
  Verteilen2__Vault__DataDoubleEntry **data_double;
  size_t n_data_string;
  Verteilen2__Vault__DataStringEntry **data_string;
};
#define VERTEILEN2__VAULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__vault__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL }


/* Verteilen2__Vault__DataBoolEntry methods */
void   verteilen2__vault__data_bool_entry__init
                     (Verteilen2__Vault__DataBoolEntry         *message);
/* Verteilen2__Vault__DataInt32Entry methods */
void   verteilen2__vault__data_int32_entry__init
                     (Verteilen2__Vault__DataInt32Entry         *message);
/* Verteilen2__Vault__DataInt64Entry methods */
void   verteilen2__vault__data_int64_entry__init
                     (Verteilen2__Vault__DataInt64Entry         *message);
/* Verteilen2__Vault__DataFloatEntry methods */
void   verteilen2__vault__data_float_entry__init
                     (Verteilen2__Vault__DataFloatEntry         *message);
/* Verteilen2__Vault__DataDoubleEntry methods */
void   verteilen2__vault__data_double_entry__init
                     (Verteilen2__Vault__DataDoubleEntry         *message);
/* Verteilen2__Vault__DataStringEntry methods */
void   verteilen2__vault__data_string_entry__init
                     (Verteilen2__Vault__DataStringEntry         *message);
/* Verteilen2__Vault methods */
void   verteilen2__vault__init
                     (Verteilen2__Vault         *message);
size_t verteilen2__vault__get_packed_size
                     (const Verteilen2__Vault   *message);
size_t verteilen2__vault__pack
                     (const Verteilen2__Vault   *message,
                      uint8_t             *out);
size_t verteilen2__vault__pack_to_buffer
                     (const Verteilen2__Vault   *message,
                      ProtobufCBuffer     *buffer);
Verteilen2__Vault *
       verteilen2__vault__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   verteilen2__vault__free_unpacked
                     (Verteilen2__Vault *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Verteilen2__Vault__DataBoolEntry_Closure)
                 (const Verteilen2__Vault__DataBoolEntry *message,
                  void *closure_data);
typedef void (*Verteilen2__Vault__DataInt32Entry_Closure)
                 (const Verteilen2__Vault__DataInt32Entry *message,
                  void *closure_data);
typedef void (*Verteilen2__Vault__DataInt64Entry_Closure)
                 (const Verteilen2__Vault__DataInt64Entry *message,
                  void *closure_data);
typedef void (*Verteilen2__Vault__DataFloatEntry_Closure)
                 (const Verteilen2__Vault__DataFloatEntry *message,
                  void *closure_data);
typedef void (*Verteilen2__Vault__DataDoubleEntry_Closure)
                 (const Verteilen2__Vault__DataDoubleEntry *message,
                  void *closure_data);
typedef void (*Verteilen2__Vault__DataStringEntry_Closure)
                 (const Verteilen2__Vault__DataStringEntry *message,
                  void *closure_data);
typedef void (*Verteilen2__Vault_Closure)
                 (const Verteilen2__Vault *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor verteilen2__vault__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__vault__data_bool_entry__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__vault__data_int32_entry__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__vault__data_int64_entry__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__vault__data_float_entry__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__vault__data_double_entry__descriptor;
extern const ProtobufCMessageDescriptor verteilen2__vault__data_string_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_vault_2eproto__INCLUDED */
