/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: debug_log.proto */

#ifndef PROTOBUF_C_debug_5flog_2eproto__INCLUDED
#define PROTOBUF_C_debug_5flog_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Verteilen2__DebugLog Verteilen2__DebugLog;


/* --- enums --- */


/* --- messages --- */

/*
 * MsgType: DEBUG_LOG
 */
struct  Verteilen2__DebugLog
{
  ProtobufCMessage base;
  char *uuid;
  char *title;
  char *content;
};
#define VERTEILEN2__DEBUG_LOG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&verteilen2__debug_log__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Verteilen2__DebugLog methods */
void   verteilen2__debug_log__init
                     (Verteilen2__DebugLog         *message);
size_t verteilen2__debug_log__get_packed_size
                     (const Verteilen2__DebugLog   *message);
size_t verteilen2__debug_log__pack
                     (const Verteilen2__DebugLog   *message,
                      uint8_t             *out);
size_t verteilen2__debug_log__pack_to_buffer
                     (const Verteilen2__DebugLog   *message,
                      ProtobufCBuffer     *buffer);
Verteilen2__DebugLog *
       verteilen2__debug_log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   verteilen2__debug_log__free_unpacked
                     (Verteilen2__DebugLog *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Verteilen2__DebugLog_Closure)
                 (const Verteilen2__DebugLog *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor verteilen2__debug_log__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_debug_5flog_2eproto__INCLUDED */
