// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: struct_job.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_struct_5fjob_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_struct_5fjob_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "struct_dynamic_map.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_struct_5fjob_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_struct_5fjob_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_struct_5fjob_2eproto;
namespace verteilen2 {
class Job;
struct JobDefaultTypeInternal;
extern JobDefaultTypeInternal _Job_default_instance_;
}  // namespace verteilen2
PROTOBUF_NAMESPACE_OPEN
template<> ::verteilen2::Job* Arena::CreateMaybeMessage<::verteilen2::Job>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace verteilen2 {

// ===================================================================

class Job final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:verteilen2.Job) */ {
 public:
  inline Job() : Job(nullptr) {}
  ~Job() override;
  explicit PROTOBUF_CONSTEXPR Job(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Job(const Job& from);
  Job(Job&& from) noexcept
    : Job() {
    *this = ::std::move(from);
  }

  inline Job& operator=(const Job& from) {
    CopyFrom(from);
    return *this;
  }
  inline Job& operator=(Job&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Job& default_instance() {
    return *internal_default_instance();
  }
  static inline const Job* internal_default_instance() {
    return reinterpret_cast<const Job*>(
               &_Job_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Job& a, Job& b) {
    a.Swap(&b);
  }
  inline void Swap(Job* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Job* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Job* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Job>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Job& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Job& from) {
    Job::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Job* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "verteilen2.Job";
  }
  protected:
  explicit Job(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUuidFieldNumber = 1,
    kNameFieldNumber = 2,
    kScriptFieldNumber = 4,
    kInputs0FieldNumber = 6,
    kInputs1FieldNumber = 7,
    kInputs2FieldNumber = 8,
    kInputs3FieldNumber = 9,
    kInputs4FieldNumber = 10,
    kDMapFieldNumber = 5,
    kTypeFieldNumber = 3,
  };
  // string uuid = 1;
  void clear_uuid();
  const std::string& uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string script = 4;
  void clear_script();
  const std::string& script() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_script(ArgT0&& arg0, ArgT... args);
  std::string* mutable_script();
  PROTOBUF_NODISCARD std::string* release_script();
  void set_allocated_script(std::string* script);
  private:
  const std::string& _internal_script() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_script(const std::string& value);
  std::string* _internal_mutable_script();
  public:

  // string inputs_0 = 6;
  void clear_inputs_0();
  const std::string& inputs_0() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inputs_0(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inputs_0();
  PROTOBUF_NODISCARD std::string* release_inputs_0();
  void set_allocated_inputs_0(std::string* inputs_0);
  private:
  const std::string& _internal_inputs_0() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inputs_0(const std::string& value);
  std::string* _internal_mutable_inputs_0();
  public:

  // string inputs_1 = 7;
  void clear_inputs_1();
  const std::string& inputs_1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inputs_1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inputs_1();
  PROTOBUF_NODISCARD std::string* release_inputs_1();
  void set_allocated_inputs_1(std::string* inputs_1);
  private:
  const std::string& _internal_inputs_1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inputs_1(const std::string& value);
  std::string* _internal_mutable_inputs_1();
  public:

  // string inputs_2 = 8;
  void clear_inputs_2();
  const std::string& inputs_2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inputs_2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inputs_2();
  PROTOBUF_NODISCARD std::string* release_inputs_2();
  void set_allocated_inputs_2(std::string* inputs_2);
  private:
  const std::string& _internal_inputs_2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inputs_2(const std::string& value);
  std::string* _internal_mutable_inputs_2();
  public:

  // string inputs_3 = 9;
  void clear_inputs_3();
  const std::string& inputs_3() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inputs_3(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inputs_3();
  PROTOBUF_NODISCARD std::string* release_inputs_3();
  void set_allocated_inputs_3(std::string* inputs_3);
  private:
  const std::string& _internal_inputs_3() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inputs_3(const std::string& value);
  std::string* _internal_mutable_inputs_3();
  public:

  // string inputs_4 = 10;
  void clear_inputs_4();
  const std::string& inputs_4() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inputs_4(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inputs_4();
  PROTOBUF_NODISCARD std::string* release_inputs_4();
  void set_allocated_inputs_4(std::string* inputs_4);
  private:
  const std::string& _internal_inputs_4() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inputs_4(const std::string& value);
  std::string* _internal_mutable_inputs_4();
  public:

  // .verteilen2.DynamicMap d_map = 5;
  bool has_d_map() const;
  private:
  bool _internal_has_d_map() const;
  public:
  void clear_d_map();
  const ::verteilen2::DynamicMap& d_map() const;
  PROTOBUF_NODISCARD ::verteilen2::DynamicMap* release_d_map();
  ::verteilen2::DynamicMap* mutable_d_map();
  void set_allocated_d_map(::verteilen2::DynamicMap* d_map);
  private:
  const ::verteilen2::DynamicMap& _internal_d_map() const;
  ::verteilen2::DynamicMap* _internal_mutable_d_map();
  public:
  void unsafe_arena_set_allocated_d_map(
      ::verteilen2::DynamicMap* d_map);
  ::verteilen2::DynamicMap* unsafe_arena_release_d_map();

  // int32 type = 3;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:verteilen2.Job)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr script_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputs_0_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputs_1_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputs_2_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputs_3_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputs_4_;
    ::verteilen2::DynamicMap* d_map_;
    int32_t type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_struct_5fjob_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Job

// string uuid = 1;
inline void Job::clear_uuid() {
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& Job::uuid() const {
  // @@protoc_insertion_point(field_get:verteilen2.Job.uuid)
  return _internal_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Job::set_uuid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.uuid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Job.uuid)
}
inline std::string* Job::mutable_uuid() {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:verteilen2.Job.uuid)
  return _s;
}
inline const std::string& Job::_internal_uuid() const {
  return _impl_.uuid_.Get();
}
inline void Job::_internal_set_uuid(const std::string& value) {
  
  _impl_.uuid_.Set(value, GetArenaForAllocation());
}
inline std::string* Job::_internal_mutable_uuid() {
  
  return _impl_.uuid_.Mutable(GetArenaForAllocation());
}
inline std::string* Job::release_uuid() {
  // @@protoc_insertion_point(field_release:verteilen2.Job.uuid)
  return _impl_.uuid_.Release();
}
inline void Job::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  _impl_.uuid_.SetAllocated(uuid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Job.uuid)
}

// string name = 2;
inline void Job::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Job::name() const {
  // @@protoc_insertion_point(field_get:verteilen2.Job.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Job::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Job.name)
}
inline std::string* Job::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:verteilen2.Job.name)
  return _s;
}
inline const std::string& Job::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Job::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Job::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Job::release_name() {
  // @@protoc_insertion_point(field_release:verteilen2.Job.name)
  return _impl_.name_.Release();
}
inline void Job::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Job.name)
}

// int32 type = 3;
inline void Job::clear_type() {
  _impl_.type_ = 0;
}
inline int32_t Job::_internal_type() const {
  return _impl_.type_;
}
inline int32_t Job::type() const {
  // @@protoc_insertion_point(field_get:verteilen2.Job.type)
  return _internal_type();
}
inline void Job::_internal_set_type(int32_t value) {
  
  _impl_.type_ = value;
}
inline void Job::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:verteilen2.Job.type)
}

// string script = 4;
inline void Job::clear_script() {
  _impl_.script_.ClearToEmpty();
}
inline const std::string& Job::script() const {
  // @@protoc_insertion_point(field_get:verteilen2.Job.script)
  return _internal_script();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Job::set_script(ArgT0&& arg0, ArgT... args) {
 
 _impl_.script_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Job.script)
}
inline std::string* Job::mutable_script() {
  std::string* _s = _internal_mutable_script();
  // @@protoc_insertion_point(field_mutable:verteilen2.Job.script)
  return _s;
}
inline const std::string& Job::_internal_script() const {
  return _impl_.script_.Get();
}
inline void Job::_internal_set_script(const std::string& value) {
  
  _impl_.script_.Set(value, GetArenaForAllocation());
}
inline std::string* Job::_internal_mutable_script() {
  
  return _impl_.script_.Mutable(GetArenaForAllocation());
}
inline std::string* Job::release_script() {
  // @@protoc_insertion_point(field_release:verteilen2.Job.script)
  return _impl_.script_.Release();
}
inline void Job::set_allocated_script(std::string* script) {
  if (script != nullptr) {
    
  } else {
    
  }
  _impl_.script_.SetAllocated(script, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.script_.IsDefault()) {
    _impl_.script_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Job.script)
}

// .verteilen2.DynamicMap d_map = 5;
inline bool Job::_internal_has_d_map() const {
  return this != internal_default_instance() && _impl_.d_map_ != nullptr;
}
inline bool Job::has_d_map() const {
  return _internal_has_d_map();
}
inline const ::verteilen2::DynamicMap& Job::_internal_d_map() const {
  const ::verteilen2::DynamicMap* p = _impl_.d_map_;
  return p != nullptr ? *p : reinterpret_cast<const ::verteilen2::DynamicMap&>(
      ::verteilen2::_DynamicMap_default_instance_);
}
inline const ::verteilen2::DynamicMap& Job::d_map() const {
  // @@protoc_insertion_point(field_get:verteilen2.Job.d_map)
  return _internal_d_map();
}
inline void Job::unsafe_arena_set_allocated_d_map(
    ::verteilen2::DynamicMap* d_map) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.d_map_);
  }
  _impl_.d_map_ = d_map;
  if (d_map) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:verteilen2.Job.d_map)
}
inline ::verteilen2::DynamicMap* Job::release_d_map() {
  
  ::verteilen2::DynamicMap* temp = _impl_.d_map_;
  _impl_.d_map_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::verteilen2::DynamicMap* Job::unsafe_arena_release_d_map() {
  // @@protoc_insertion_point(field_release:verteilen2.Job.d_map)
  
  ::verteilen2::DynamicMap* temp = _impl_.d_map_;
  _impl_.d_map_ = nullptr;
  return temp;
}
inline ::verteilen2::DynamicMap* Job::_internal_mutable_d_map() {
  
  if (_impl_.d_map_ == nullptr) {
    auto* p = CreateMaybeMessage<::verteilen2::DynamicMap>(GetArenaForAllocation());
    _impl_.d_map_ = p;
  }
  return _impl_.d_map_;
}
inline ::verteilen2::DynamicMap* Job::mutable_d_map() {
  ::verteilen2::DynamicMap* _msg = _internal_mutable_d_map();
  // @@protoc_insertion_point(field_mutable:verteilen2.Job.d_map)
  return _msg;
}
inline void Job::set_allocated_d_map(::verteilen2::DynamicMap* d_map) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.d_map_);
  }
  if (d_map) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(d_map));
    if (message_arena != submessage_arena) {
      d_map = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, d_map, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.d_map_ = d_map;
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Job.d_map)
}

// string inputs_0 = 6;
inline void Job::clear_inputs_0() {
  _impl_.inputs_0_.ClearToEmpty();
}
inline const std::string& Job::inputs_0() const {
  // @@protoc_insertion_point(field_get:verteilen2.Job.inputs_0)
  return _internal_inputs_0();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Job::set_inputs_0(ArgT0&& arg0, ArgT... args) {
 
 _impl_.inputs_0_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Job.inputs_0)
}
inline std::string* Job::mutable_inputs_0() {
  std::string* _s = _internal_mutable_inputs_0();
  // @@protoc_insertion_point(field_mutable:verteilen2.Job.inputs_0)
  return _s;
}
inline const std::string& Job::_internal_inputs_0() const {
  return _impl_.inputs_0_.Get();
}
inline void Job::_internal_set_inputs_0(const std::string& value) {
  
  _impl_.inputs_0_.Set(value, GetArenaForAllocation());
}
inline std::string* Job::_internal_mutable_inputs_0() {
  
  return _impl_.inputs_0_.Mutable(GetArenaForAllocation());
}
inline std::string* Job::release_inputs_0() {
  // @@protoc_insertion_point(field_release:verteilen2.Job.inputs_0)
  return _impl_.inputs_0_.Release();
}
inline void Job::set_allocated_inputs_0(std::string* inputs_0) {
  if (inputs_0 != nullptr) {
    
  } else {
    
  }
  _impl_.inputs_0_.SetAllocated(inputs_0, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inputs_0_.IsDefault()) {
    _impl_.inputs_0_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Job.inputs_0)
}

// string inputs_1 = 7;
inline void Job::clear_inputs_1() {
  _impl_.inputs_1_.ClearToEmpty();
}
inline const std::string& Job::inputs_1() const {
  // @@protoc_insertion_point(field_get:verteilen2.Job.inputs_1)
  return _internal_inputs_1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Job::set_inputs_1(ArgT0&& arg0, ArgT... args) {
 
 _impl_.inputs_1_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Job.inputs_1)
}
inline std::string* Job::mutable_inputs_1() {
  std::string* _s = _internal_mutable_inputs_1();
  // @@protoc_insertion_point(field_mutable:verteilen2.Job.inputs_1)
  return _s;
}
inline const std::string& Job::_internal_inputs_1() const {
  return _impl_.inputs_1_.Get();
}
inline void Job::_internal_set_inputs_1(const std::string& value) {
  
  _impl_.inputs_1_.Set(value, GetArenaForAllocation());
}
inline std::string* Job::_internal_mutable_inputs_1() {
  
  return _impl_.inputs_1_.Mutable(GetArenaForAllocation());
}
inline std::string* Job::release_inputs_1() {
  // @@protoc_insertion_point(field_release:verteilen2.Job.inputs_1)
  return _impl_.inputs_1_.Release();
}
inline void Job::set_allocated_inputs_1(std::string* inputs_1) {
  if (inputs_1 != nullptr) {
    
  } else {
    
  }
  _impl_.inputs_1_.SetAllocated(inputs_1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inputs_1_.IsDefault()) {
    _impl_.inputs_1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Job.inputs_1)
}

// string inputs_2 = 8;
inline void Job::clear_inputs_2() {
  _impl_.inputs_2_.ClearToEmpty();
}
inline const std::string& Job::inputs_2() const {
  // @@protoc_insertion_point(field_get:verteilen2.Job.inputs_2)
  return _internal_inputs_2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Job::set_inputs_2(ArgT0&& arg0, ArgT... args) {
 
 _impl_.inputs_2_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Job.inputs_2)
}
inline std::string* Job::mutable_inputs_2() {
  std::string* _s = _internal_mutable_inputs_2();
  // @@protoc_insertion_point(field_mutable:verteilen2.Job.inputs_2)
  return _s;
}
inline const std::string& Job::_internal_inputs_2() const {
  return _impl_.inputs_2_.Get();
}
inline void Job::_internal_set_inputs_2(const std::string& value) {
  
  _impl_.inputs_2_.Set(value, GetArenaForAllocation());
}
inline std::string* Job::_internal_mutable_inputs_2() {
  
  return _impl_.inputs_2_.Mutable(GetArenaForAllocation());
}
inline std::string* Job::release_inputs_2() {
  // @@protoc_insertion_point(field_release:verteilen2.Job.inputs_2)
  return _impl_.inputs_2_.Release();
}
inline void Job::set_allocated_inputs_2(std::string* inputs_2) {
  if (inputs_2 != nullptr) {
    
  } else {
    
  }
  _impl_.inputs_2_.SetAllocated(inputs_2, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inputs_2_.IsDefault()) {
    _impl_.inputs_2_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Job.inputs_2)
}

// string inputs_3 = 9;
inline void Job::clear_inputs_3() {
  _impl_.inputs_3_.ClearToEmpty();
}
inline const std::string& Job::inputs_3() const {
  // @@protoc_insertion_point(field_get:verteilen2.Job.inputs_3)
  return _internal_inputs_3();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Job::set_inputs_3(ArgT0&& arg0, ArgT... args) {
 
 _impl_.inputs_3_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Job.inputs_3)
}
inline std::string* Job::mutable_inputs_3() {
  std::string* _s = _internal_mutable_inputs_3();
  // @@protoc_insertion_point(field_mutable:verteilen2.Job.inputs_3)
  return _s;
}
inline const std::string& Job::_internal_inputs_3() const {
  return _impl_.inputs_3_.Get();
}
inline void Job::_internal_set_inputs_3(const std::string& value) {
  
  _impl_.inputs_3_.Set(value, GetArenaForAllocation());
}
inline std::string* Job::_internal_mutable_inputs_3() {
  
  return _impl_.inputs_3_.Mutable(GetArenaForAllocation());
}
inline std::string* Job::release_inputs_3() {
  // @@protoc_insertion_point(field_release:verteilen2.Job.inputs_3)
  return _impl_.inputs_3_.Release();
}
inline void Job::set_allocated_inputs_3(std::string* inputs_3) {
  if (inputs_3 != nullptr) {
    
  } else {
    
  }
  _impl_.inputs_3_.SetAllocated(inputs_3, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inputs_3_.IsDefault()) {
    _impl_.inputs_3_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Job.inputs_3)
}

// string inputs_4 = 10;
inline void Job::clear_inputs_4() {
  _impl_.inputs_4_.ClearToEmpty();
}
inline const std::string& Job::inputs_4() const {
  // @@protoc_insertion_point(field_get:verteilen2.Job.inputs_4)
  return _internal_inputs_4();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Job::set_inputs_4(ArgT0&& arg0, ArgT... args) {
 
 _impl_.inputs_4_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:verteilen2.Job.inputs_4)
}
inline std::string* Job::mutable_inputs_4() {
  std::string* _s = _internal_mutable_inputs_4();
  // @@protoc_insertion_point(field_mutable:verteilen2.Job.inputs_4)
  return _s;
}
inline const std::string& Job::_internal_inputs_4() const {
  return _impl_.inputs_4_.Get();
}
inline void Job::_internal_set_inputs_4(const std::string& value) {
  
  _impl_.inputs_4_.Set(value, GetArenaForAllocation());
}
inline std::string* Job::_internal_mutable_inputs_4() {
  
  return _impl_.inputs_4_.Mutable(GetArenaForAllocation());
}
inline std::string* Job::release_inputs_4() {
  // @@protoc_insertion_point(field_release:verteilen2.Job.inputs_4)
  return _impl_.inputs_4_.Release();
}
inline void Job::set_allocated_inputs_4(std::string* inputs_4) {
  if (inputs_4 != nullptr) {
    
  } else {
    
  }
  _impl_.inputs_4_.SetAllocated(inputs_4, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inputs_4_.IsDefault()) {
    _impl_.inputs_4_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:verteilen2.Job.inputs_4)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace verteilen2

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_struct_5fjob_2eproto
