// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action_client/file_system.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_action_5fclient_2ffile_5fsystem_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_action_5fclient_2ffile_5fsystem_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "file_system.pb.h"
#include "enum/action_fs_type.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_action_5fclient_2ffile_5fsystem_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_action_5fclient_2ffile_5fsystem_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_action_5fclient_2ffile_5fsystem_2eproto;
namespace verteilen2 {
namespace action {
namespace client {
class FileSystem;
struct FileSystemDefaultTypeInternal;
extern FileSystemDefaultTypeInternal _FileSystem_default_instance_;
}  // namespace client
}  // namespace action
}  // namespace verteilen2
PROTOBUF_NAMESPACE_OPEN
template<> ::verteilen2::action::client::FileSystem* Arena::CreateMaybeMessage<::verteilen2::action::client::FileSystem>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace verteilen2 {
namespace action {
namespace client {

// ===================================================================

class FileSystem final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:verteilen2.action.client.FileSystem) */ {
 public:
  inline FileSystem() : FileSystem(nullptr) {}
  ~FileSystem() override;
  explicit PROTOBUF_CONSTEXPR FileSystem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileSystem(const FileSystem& from);
  FileSystem(FileSystem&& from) noexcept
    : FileSystem() {
    *this = ::std::move(from);
  }

  inline FileSystem& operator=(const FileSystem& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileSystem& operator=(FileSystem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileSystem& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileSystem* internal_default_instance() {
    return reinterpret_cast<const FileSystem*>(
               &_FileSystem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FileSystem& a, FileSystem& b) {
    a.Swap(&b);
  }
  inline void Swap(FileSystem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileSystem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileSystem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileSystem>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileSystem& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileSystem& from) {
    FileSystem::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileSystem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "verteilen2.action.client.FileSystem";
  }
  protected:
  explicit FileSystem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFsFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // .verteilen2.action.client.FileSystem fs = 2;
  bool has_fs() const;
  private:
  bool _internal_has_fs() const;
  public:
  void clear_fs();
  const ::verteilen2::action::client::FileSystem& fs() const;
  PROTOBUF_NODISCARD ::verteilen2::action::client::FileSystem* release_fs();
  ::verteilen2::action::client::FileSystem* mutable_fs();
  void set_allocated_fs(::verteilen2::action::client::FileSystem* fs);
  private:
  const ::verteilen2::action::client::FileSystem& _internal_fs() const;
  ::verteilen2::action::client::FileSystem* _internal_mutable_fs();
  public:
  void unsafe_arena_set_allocated_fs(
      ::verteilen2::action::client::FileSystem* fs);
  ::verteilen2::action::client::FileSystem* unsafe_arena_release_fs();

  // .verteilen2.ActionFSType type = 1;
  void clear_type();
  ::verteilen2::ActionFSType type() const;
  void set_type(::verteilen2::ActionFSType value);
  private:
  ::verteilen2::ActionFSType _internal_type() const;
  void _internal_set_type(::verteilen2::ActionFSType value);
  public:

  // @@protoc_insertion_point(class_scope:verteilen2.action.client.FileSystem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::verteilen2::action::client::FileSystem* fs_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_action_5fclient_2ffile_5fsystem_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FileSystem

// .verteilen2.ActionFSType type = 1;
inline void FileSystem::clear_type() {
  _impl_.type_ = 0;
}
inline ::verteilen2::ActionFSType FileSystem::_internal_type() const {
  return static_cast< ::verteilen2::ActionFSType >(_impl_.type_);
}
inline ::verteilen2::ActionFSType FileSystem::type() const {
  // @@protoc_insertion_point(field_get:verteilen2.action.client.FileSystem.type)
  return _internal_type();
}
inline void FileSystem::_internal_set_type(::verteilen2::ActionFSType value) {
  
  _impl_.type_ = value;
}
inline void FileSystem::set_type(::verteilen2::ActionFSType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:verteilen2.action.client.FileSystem.type)
}

// .verteilen2.action.client.FileSystem fs = 2;
inline bool FileSystem::_internal_has_fs() const {
  return this != internal_default_instance() && _impl_.fs_ != nullptr;
}
inline bool FileSystem::has_fs() const {
  return _internal_has_fs();
}
inline void FileSystem::clear_fs() {
  if (GetArenaForAllocation() == nullptr && _impl_.fs_ != nullptr) {
    delete _impl_.fs_;
  }
  _impl_.fs_ = nullptr;
}
inline const ::verteilen2::action::client::FileSystem& FileSystem::_internal_fs() const {
  const ::verteilen2::action::client::FileSystem* p = _impl_.fs_;
  return p != nullptr ? *p : reinterpret_cast<const ::verteilen2::action::client::FileSystem&>(
      ::verteilen2::action::client::_FileSystem_default_instance_);
}
inline const ::verteilen2::action::client::FileSystem& FileSystem::fs() const {
  // @@protoc_insertion_point(field_get:verteilen2.action.client.FileSystem.fs)
  return _internal_fs();
}
inline void FileSystem::unsafe_arena_set_allocated_fs(
    ::verteilen2::action::client::FileSystem* fs) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.fs_);
  }
  _impl_.fs_ = fs;
  if (fs) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:verteilen2.action.client.FileSystem.fs)
}
inline ::verteilen2::action::client::FileSystem* FileSystem::release_fs() {
  
  ::verteilen2::action::client::FileSystem* temp = _impl_.fs_;
  _impl_.fs_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::verteilen2::action::client::FileSystem* FileSystem::unsafe_arena_release_fs() {
  // @@protoc_insertion_point(field_release:verteilen2.action.client.FileSystem.fs)
  
  ::verteilen2::action::client::FileSystem* temp = _impl_.fs_;
  _impl_.fs_ = nullptr;
  return temp;
}
inline ::verteilen2::action::client::FileSystem* FileSystem::_internal_mutable_fs() {
  
  if (_impl_.fs_ == nullptr) {
    auto* p = CreateMaybeMessage<::verteilen2::action::client::FileSystem>(GetArenaForAllocation());
    _impl_.fs_ = p;
  }
  return _impl_.fs_;
}
inline ::verteilen2::action::client::FileSystem* FileSystem::mutable_fs() {
  ::verteilen2::action::client::FileSystem* _msg = _internal_mutable_fs();
  // @@protoc_insertion_point(field_mutable:verteilen2.action.client.FileSystem.fs)
  return _msg;
}
inline void FileSystem::set_allocated_fs(::verteilen2::action::client::FileSystem* fs) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.fs_;
  }
  if (fs) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(fs);
    if (message_arena != submessage_arena) {
      fs = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, fs, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.fs_ = fs;
  // @@protoc_insertion_point(field_set_allocated:verteilen2.action.client.FileSystem.fs)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace client
}  // namespace action
}  // namespace verteilen2

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_action_5fclient_2ffile_5fsystem_2eproto
