// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_file_system.proto

#include "client_file_system.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace verteilen2 {
namespace client {
PROTOBUF_CONSTEXPR FileSystem::FileSystem(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.fs_)*/nullptr
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FileSystemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileSystemDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileSystemDefaultTypeInternal() {}
  union {
    FileSystem _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileSystemDefaultTypeInternal _FileSystem_default_instance_;
}  // namespace client
}  // namespace verteilen2
static ::_pb::Metadata file_level_metadata_client_5ffile_5fsystem_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_client_5ffile_5fsystem_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_client_5ffile_5fsystem_2eproto = nullptr;

const uint32_t TableStruct_client_5ffile_5fsystem_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::verteilen2::client::FileSystem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::verteilen2::client::FileSystem, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::verteilen2::client::FileSystem, _impl_.fs_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::verteilen2::client::FileSystem)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::verteilen2::client::_FileSystem_default_instance_._instance,
};

const char descriptor_table_protodef_client_5ffile_5fsystem_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030client_file_system.proto\022\021verteilen2.c"
  "lient\032\031enum_action_fs_type.proto\"_\n\nFile"
  "System\022&\n\004type\030\001 \001(\0162\030.verteilen2.Action"
  "FSType\022)\n\002fs\030\002 \001(\0132\035.verteilen2.client.F"
  "ileSystemb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_client_5ffile_5fsystem_2eproto_deps[1] = {
  &::descriptor_table_enum_5faction_5ffs_5ftype_2eproto,
};
static ::_pbi::once_flag descriptor_table_client_5ffile_5fsystem_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_client_5ffile_5fsystem_2eproto = {
    false, false, 177, descriptor_table_protodef_client_5ffile_5fsystem_2eproto,
    "client_file_system.proto",
    &descriptor_table_client_5ffile_5fsystem_2eproto_once, descriptor_table_client_5ffile_5fsystem_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_client_5ffile_5fsystem_2eproto::offsets,
    file_level_metadata_client_5ffile_5fsystem_2eproto, file_level_enum_descriptors_client_5ffile_5fsystem_2eproto,
    file_level_service_descriptors_client_5ffile_5fsystem_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_client_5ffile_5fsystem_2eproto_getter() {
  return &descriptor_table_client_5ffile_5fsystem_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_client_5ffile_5fsystem_2eproto(&descriptor_table_client_5ffile_5fsystem_2eproto);
namespace verteilen2 {
namespace client {

// ===================================================================

class FileSystem::_Internal {
 public:
  static const ::verteilen2::client::FileSystem& fs(const FileSystem* msg);
};

const ::verteilen2::client::FileSystem&
FileSystem::_Internal::fs(const FileSystem* msg) {
  return *msg->_impl_.fs_;
}
FileSystem::FileSystem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:verteilen2.client.FileSystem)
}
FileSystem::FileSystem(const FileSystem& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FileSystem* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.fs_){nullptr}
    , decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_fs()) {
    _this->_impl_.fs_ = new ::verteilen2::client::FileSystem(*from._impl_.fs_);
  }
  _this->_impl_.type_ = from._impl_.type_;
  // @@protoc_insertion_point(copy_constructor:verteilen2.client.FileSystem)
}

inline void FileSystem::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.fs_){nullptr}
    , decltype(_impl_.type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

FileSystem::~FileSystem() {
  // @@protoc_insertion_point(destructor:verteilen2.client.FileSystem)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FileSystem::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.fs_;
}

void FileSystem::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FileSystem::Clear() {
// @@protoc_insertion_point(message_clear_start:verteilen2.client.FileSystem)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.fs_ != nullptr) {
    delete _impl_.fs_;
  }
  _impl_.fs_ = nullptr;
  _impl_.type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FileSystem::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .verteilen2.ActionFSType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::verteilen2::ActionFSType>(val));
        } else
          goto handle_unusual;
        continue;
      // .verteilen2.client.FileSystem fs = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_fs(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FileSystem::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:verteilen2.client.FileSystem)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .verteilen2.ActionFSType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // .verteilen2.client.FileSystem fs = 2;
  if (this->_internal_has_fs()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::fs(this),
        _Internal::fs(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:verteilen2.client.FileSystem)
  return target;
}

size_t FileSystem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:verteilen2.client.FileSystem)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .verteilen2.client.FileSystem fs = 2;
  if (this->_internal_has_fs()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.fs_);
  }

  // .verteilen2.ActionFSType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FileSystem::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FileSystem::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FileSystem::GetClassData() const { return &_class_data_; }


void FileSystem::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FileSystem*>(&to_msg);
  auto& from = static_cast<const FileSystem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:verteilen2.client.FileSystem)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_fs()) {
    _this->_internal_mutable_fs()->::verteilen2::client::FileSystem::MergeFrom(
        from._internal_fs());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FileSystem::CopyFrom(const FileSystem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:verteilen2.client.FileSystem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FileSystem::IsInitialized() const {
  return true;
}

void FileSystem::InternalSwap(FileSystem* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileSystem, _impl_.type_)
      + sizeof(FileSystem::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(FileSystem, _impl_.fs_)>(
          reinterpret_cast<char*>(&_impl_.fs_),
          reinterpret_cast<char*>(&other->_impl_.fs_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FileSystem::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_client_5ffile_5fsystem_2eproto_getter, &descriptor_table_client_5ffile_5fsystem_2eproto_once,
      file_level_metadata_client_5ffile_5fsystem_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace client
}  // namespace verteilen2
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::verteilen2::client::FileSystem*
Arena::CreateMaybeMessage< ::verteilen2::client::FileSystem >(Arena* arena) {
  return Arena::CreateMessageInternal< ::verteilen2::client::FileSystem >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
