/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cron.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cron.pb-c.h"
void   verteilen2__cron__init
                     (Verteilen2__Cron         *message)
{
  static const Verteilen2__Cron init_value = VERTEILEN2__CRON__INIT;
  *message = init_value;
}
size_t verteilen2__cron__get_packed_size
                     (const Verteilen2__Cron *message)
{
  assert(message->base.descriptor == &verteilen2__cron__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t verteilen2__cron__pack
                     (const Verteilen2__Cron *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &verteilen2__cron__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t verteilen2__cron__pack_to_buffer
                     (const Verteilen2__Cron *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &verteilen2__cron__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Verteilen2__Cron *
       verteilen2__cron__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Verteilen2__Cron *)
     protobuf_c_message_unpack (&verteilen2__cron__descriptor,
                                allocator, len, data);
}
void   verteilen2__cron__free_unpacked
                     (Verteilen2__Cron *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &verteilen2__cron__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor verteilen2__cron__field_descriptors[4] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Cron, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Cron, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Cron, description),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "project",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Cron, project),
    &verteilen2__data_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__cron__field_indices_by_name[] = {
  2,   /* field[2] = description */
  1,   /* field[1] = name */
  3,   /* field[3] = project */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange verteilen2__cron__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor verteilen2__cron__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.Cron",
  "Cron",
  "Verteilen2__Cron",
  "verteilen2",
  sizeof(Verteilen2__Cron),
  4,
  verteilen2__cron__field_descriptors,
  verteilen2__cron__field_indices_by_name,
  1,  verteilen2__cron__number_ranges,
  (ProtobufCMessageInit) verteilen2__cron__init,
  NULL,NULL,NULL    /* reserved[123] */
};
