/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: execute_job.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "execute_job.pb-c.h"
void   verteilen2__execute_job__map_boolean_entry__init
                     (Verteilen2__ExecuteJob__MapBooleanEntry         *message)
{
  static const Verteilen2__ExecuteJob__MapBooleanEntry init_value = VERTEILEN2__EXECUTE_JOB__MAP_BOOLEAN_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__execute_job__map_int32_entry__init
                     (Verteilen2__ExecuteJob__MapInt32Entry         *message)
{
  static const Verteilen2__ExecuteJob__MapInt32Entry init_value = VERTEILEN2__EXECUTE_JOB__MAP_INT32_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__execute_job__map_int64_entry__init
                     (Verteilen2__ExecuteJob__MapInt64Entry         *message)
{
  static const Verteilen2__ExecuteJob__MapInt64Entry init_value = VERTEILEN2__EXECUTE_JOB__MAP_INT64_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__execute_job__map_float_entry__init
                     (Verteilen2__ExecuteJob__MapFloatEntry         *message)
{
  static const Verteilen2__ExecuteJob__MapFloatEntry init_value = VERTEILEN2__EXECUTE_JOB__MAP_FLOAT_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__execute_job__map_double_entry__init
                     (Verteilen2__ExecuteJob__MapDoubleEntry         *message)
{
  static const Verteilen2__ExecuteJob__MapDoubleEntry init_value = VERTEILEN2__EXECUTE_JOB__MAP_DOUBLE_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__execute_job__map_string_entry__init
                     (Verteilen2__ExecuteJob__MapStringEntry         *message)
{
  static const Verteilen2__ExecuteJob__MapStringEntry init_value = VERTEILEN2__EXECUTE_JOB__MAP_STRING_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__execute_job__init
                     (Verteilen2__ExecuteJob         *message)
{
  static const Verteilen2__ExecuteJob init_value = VERTEILEN2__EXECUTE_JOB__INIT;
  *message = init_value;
}
size_t verteilen2__execute_job__get_packed_size
                     (const Verteilen2__ExecuteJob *message)
{
  assert(message->base.descriptor == &verteilen2__execute_job__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t verteilen2__execute_job__pack
                     (const Verteilen2__ExecuteJob *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &verteilen2__execute_job__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t verteilen2__execute_job__pack_to_buffer
                     (const Verteilen2__ExecuteJob *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &verteilen2__execute_job__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Verteilen2__ExecuteJob *
       verteilen2__execute_job__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Verteilen2__ExecuteJob *)
     protobuf_c_message_unpack (&verteilen2__execute_job__descriptor,
                                allocator, len, data);
}
void   verteilen2__execute_job__free_unpacked
                     (Verteilen2__ExecuteJob *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &verteilen2__execute_job__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor verteilen2__execute_job__map_boolean_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapBooleanEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapBooleanEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__execute_job__map_boolean_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__execute_job__map_boolean_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__execute_job__map_boolean_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.ExecuteJob.MapBooleanEntry",
  "MapBooleanEntry",
  "Verteilen2__ExecuteJob__MapBooleanEntry",
  "verteilen2",
  sizeof(Verteilen2__ExecuteJob__MapBooleanEntry),
  2,
  verteilen2__execute_job__map_boolean_entry__field_descriptors,
  verteilen2__execute_job__map_boolean_entry__field_indices_by_name,
  1,  verteilen2__execute_job__map_boolean_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__execute_job__map_boolean_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__execute_job__map_int32_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapInt32Entry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapInt32Entry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__execute_job__map_int32_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__execute_job__map_int32_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__execute_job__map_int32_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.ExecuteJob.MapInt32Entry",
  "MapInt32Entry",
  "Verteilen2__ExecuteJob__MapInt32Entry",
  "verteilen2",
  sizeof(Verteilen2__ExecuteJob__MapInt32Entry),
  2,
  verteilen2__execute_job__map_int32_entry__field_descriptors,
  verteilen2__execute_job__map_int32_entry__field_indices_by_name,
  1,  verteilen2__execute_job__map_int32_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__execute_job__map_int32_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__execute_job__map_int64_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapInt64Entry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapInt64Entry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__execute_job__map_int64_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__execute_job__map_int64_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__execute_job__map_int64_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.ExecuteJob.MapInt64Entry",
  "MapInt64Entry",
  "Verteilen2__ExecuteJob__MapInt64Entry",
  "verteilen2",
  sizeof(Verteilen2__ExecuteJob__MapInt64Entry),
  2,
  verteilen2__execute_job__map_int64_entry__field_descriptors,
  verteilen2__execute_job__map_int64_entry__field_indices_by_name,
  1,  verteilen2__execute_job__map_int64_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__execute_job__map_int64_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__execute_job__map_float_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapFloatEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapFloatEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__execute_job__map_float_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__execute_job__map_float_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__execute_job__map_float_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.ExecuteJob.MapFloatEntry",
  "MapFloatEntry",
  "Verteilen2__ExecuteJob__MapFloatEntry",
  "verteilen2",
  sizeof(Verteilen2__ExecuteJob__MapFloatEntry),
  2,
  verteilen2__execute_job__map_float_entry__field_descriptors,
  verteilen2__execute_job__map_float_entry__field_indices_by_name,
  1,  verteilen2__execute_job__map_float_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__execute_job__map_float_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__execute_job__map_double_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapDoubleEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapDoubleEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__execute_job__map_double_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__execute_job__map_double_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__execute_job__map_double_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.ExecuteJob.MapDoubleEntry",
  "MapDoubleEntry",
  "Verteilen2__ExecuteJob__MapDoubleEntry",
  "verteilen2",
  sizeof(Verteilen2__ExecuteJob__MapDoubleEntry),
  2,
  verteilen2__execute_job__map_double_entry__field_descriptors,
  verteilen2__execute_job__map_double_entry__field_indices_by_name,
  1,  verteilen2__execute_job__map_double_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__execute_job__map_double_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__execute_job__map_string_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapStringEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob__MapStringEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__execute_job__map_string_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__execute_job__map_string_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__execute_job__map_string_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.ExecuteJob.MapStringEntry",
  "MapStringEntry",
  "Verteilen2__ExecuteJob__MapStringEntry",
  "verteilen2",
  sizeof(Verteilen2__ExecuteJob__MapStringEntry),
  2,
  verteilen2__execute_job__map_string_entry__field_descriptors,
  verteilen2__execute_job__map_string_entry__field_indices_by_name,
  1,  verteilen2__execute_job__map_string_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__execute_job__map_string_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__execute_job__field_descriptors[15] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "script",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob, script),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_boolean",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__ExecuteJob, n_map_boolean),
    offsetof(Verteilen2__ExecuteJob, map_boolean),
    &verteilen2__execute_job__map_boolean_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_int32",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__ExecuteJob, n_map_int32),
    offsetof(Verteilen2__ExecuteJob, map_int32),
    &verteilen2__execute_job__map_int32_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_int64",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__ExecuteJob, n_map_int64),
    offsetof(Verteilen2__ExecuteJob, map_int64),
    &verteilen2__execute_job__map_int64_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_float",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__ExecuteJob, n_map_float),
    offsetof(Verteilen2__ExecuteJob, map_float),
    &verteilen2__execute_job__map_float_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_double",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__ExecuteJob, n_map_double),
    offsetof(Verteilen2__ExecuteJob, map_double),
    &verteilen2__execute_job__map_double_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_string",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__ExecuteJob, n_map_string),
    offsetof(Verteilen2__ExecuteJob, map_string),
    &verteilen2__execute_job__map_string_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputs_0",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob, inputs_0),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputs_1",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob, inputs_1),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputs_2",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob, inputs_2),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputs_3",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob, inputs_3),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputs_4",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__ExecuteJob, inputs_4),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__execute_job__field_indices_by_name[] = {
  0,   /* field[0] = id */
  10,   /* field[10] = inputs_0 */
  11,   /* field[11] = inputs_1 */
  12,   /* field[12] = inputs_2 */
  13,   /* field[13] = inputs_3 */
  14,   /* field[14] = inputs_4 */
  4,   /* field[4] = map_boolean */
  8,   /* field[8] = map_double */
  7,   /* field[7] = map_float */
  5,   /* field[5] = map_int32 */
  6,   /* field[6] = map_int64 */
  9,   /* field[9] = map_string */
  1,   /* field[1] = name */
  3,   /* field[3] = script */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange verteilen2__execute_job__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor verteilen2__execute_job__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.ExecuteJob",
  "ExecuteJob",
  "Verteilen2__ExecuteJob",
  "verteilen2",
  sizeof(Verteilen2__ExecuteJob),
  15,
  verteilen2__execute_job__field_descriptors,
  verteilen2__execute_job__field_indices_by_name,
  1,  verteilen2__execute_job__number_ranges,
  (ProtobufCMessageInit) verteilen2__execute_job__init,
  NULL,NULL,NULL    /* reserved[123] */
};
