/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: file_system_rule.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "file_system_rule.pb-c.h"
void   verteilen2__file_system_rule__init
                     (Verteilen2__FileSystemRule         *message)
{
  static const Verteilen2__FileSystemRule init_value = VERTEILEN2__FILE_SYSTEM_RULE__INIT;
  *message = init_value;
}
size_t verteilen2__file_system_rule__get_packed_size
                     (const Verteilen2__FileSystemRule *message)
{
  assert(message->base.descriptor == &verteilen2__file_system_rule__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t verteilen2__file_system_rule__pack
                     (const Verteilen2__FileSystemRule *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &verteilen2__file_system_rule__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t verteilen2__file_system_rule__pack_to_buffer
                     (const Verteilen2__FileSystemRule *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &verteilen2__file_system_rule__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Verteilen2__FileSystemRule *
       verteilen2__file_system_rule__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Verteilen2__FileSystemRule *)
     protobuf_c_message_unpack (&verteilen2__file_system_rule__descriptor,
                                allocator, len, data);
}
void   verteilen2__file_system_rule__free_unpacked
                     (Verteilen2__FileSystemRule *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &verteilen2__file_system_rule__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor verteilen2__file_system_rule__field_descriptors[4] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__FileSystemRule, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_uuid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__FileSystemRule, target_uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__FileSystemRule, filename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__FileSystemRule, type),
    &verteilen2__sync_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__file_system_rule__field_indices_by_name[] = {
  2,   /* field[2] = filename */
  1,   /* field[1] = target_uuid */
  3,   /* field[3] = type */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange verteilen2__file_system_rule__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor verteilen2__file_system_rule__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.FileSystemRule",
  "FileSystemRule",
  "Verteilen2__FileSystemRule",
  "verteilen2",
  sizeof(Verteilen2__FileSystemRule),
  4,
  verteilen2__file_system_rule__field_descriptors,
  verteilen2__file_system_rule__field_indices_by_name,
  1,  verteilen2__file_system_rule__number_ranges,
  (ProtobufCMessageInit) verteilen2__file_system_rule__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue verteilen2__sync_type__enum_values_by_number[4] =
{
  { "NONE", "VERTEILEN2__SYNC_TYPE__NONE", 0 },
  { "CREATE", "VERTEILEN2__SYNC_TYPE__CREATE", 1 },
  { "MODIFY", "VERTEILEN2__SYNC_TYPE__MODIFY", 2 },
  { "DELETE", "VERTEILEN2__SYNC_TYPE__DELETE", 4 },
};
static const ProtobufCIntRange verteilen2__sync_type__value_ranges[] = {
{0, 0},{4, 3},{0, 4}
};
static const ProtobufCEnumValueIndex verteilen2__sync_type__enum_values_by_name[4] =
{
  { "CREATE", 1 },
  { "DELETE", 3 },
  { "MODIFY", 2 },
  { "NONE", 0 },
};
const ProtobufCEnumDescriptor verteilen2__sync_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "verteilen2.SyncType",
  "SyncType",
  "Verteilen2__SyncType",
  "verteilen2",
  4,
  verteilen2__sync_type__enum_values_by_number,
  4,
  verteilen2__sync_type__enum_values_by_name,
  2,
  verteilen2__sync_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
