/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: node.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "node.pb-c.h"
void   verteilen2__node__init
                     (Verteilen2__Node         *message)
{
  static const Verteilen2__Node init_value = VERTEILEN2__NODE__INIT;
  *message = init_value;
}
size_t verteilen2__node__get_packed_size
                     (const Verteilen2__Node *message)
{
  assert(message->base.descriptor == &verteilen2__node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t verteilen2__node__pack
                     (const Verteilen2__Node *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &verteilen2__node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t verteilen2__node__pack_to_buffer
                     (const Verteilen2__Node *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &verteilen2__node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Verteilen2__Node *
       verteilen2__node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Verteilen2__Node *)
     protobuf_c_message_unpack (&verteilen2__node__descriptor,
                                allocator, len, data);
}
void   verteilen2__node__free_unpacked
                     (Verteilen2__Node *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &verteilen2__node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor verteilen2__node__field_descriptors[6] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Node, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Node, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Node, description),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Node, address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Node, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Verteilen2__Node, n_tag),
    offsetof(Verteilen2__Node, tag),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__node__field_indices_by_name[] = {
  3,   /* field[3] = address */
  2,   /* field[2] = description */
  1,   /* field[1] = name */
  4,   /* field[4] = port */
  5,   /* field[5] = tag */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange verteilen2__node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor verteilen2__node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.Node",
  "Node",
  "Verteilen2__Node",
  "verteilen2",
  sizeof(Verteilen2__Node),
  6,
  verteilen2__node__field_descriptors,
  verteilen2__node__field_indices_by_name,
  1,  verteilen2__node__number_ranges,
  (ProtobufCMessageInit) verteilen2__node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
