/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: task.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "task.pb-c.h"
void   verteilen2__task__init
                     (Verteilen2__Task         *message)
{
  static const Verteilen2__Task init_value = VERTEILEN2__TASK__INIT;
  *message = init_value;
}
size_t verteilen2__task__get_packed_size
                     (const Verteilen2__Task *message)
{
  assert(message->base.descriptor == &verteilen2__task__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t verteilen2__task__pack
                     (const Verteilen2__Task *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &verteilen2__task__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t verteilen2__task__pack_to_buffer
                     (const Verteilen2__Task *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &verteilen2__task__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Verteilen2__Task *
       verteilen2__task__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Verteilen2__Task *)
     protobuf_c_message_unpack (&verteilen2__task__descriptor,
                                allocator, len, data);
}
void   verteilen2__task__free_unpacked
                     (Verteilen2__Task *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &verteilen2__task__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor verteilen2__task__field_descriptors[7] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Task, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Task, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Task, description),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Task, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cluster_field_key",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Task, cluster_field_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "multicore_field_key",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Task, multicore_field_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jobs",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__Task, n_jobs),
    offsetof(Verteilen2__Task, jobs),
    &verteilen2__data_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__task__field_indices_by_name[] = {
  4,   /* field[4] = cluster_field_key */
  2,   /* field[2] = description */
  6,   /* field[6] = jobs */
  5,   /* field[5] = multicore_field_key */
  1,   /* field[1] = name */
  3,   /* field[3] = type */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange verteilen2__task__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor verteilen2__task__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.Task",
  "Task",
  "Verteilen2__Task",
  "verteilen2",
  sizeof(Verteilen2__Task),
  7,
  verteilen2__task__field_descriptors,
  verteilen2__task__field_indices_by_name,
  1,  verteilen2__task__number_ranges,
  (ProtobufCMessageInit) verteilen2__task__init,
  NULL,NULL,NULL    /* reserved[123] */
};
