/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vault.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "vault.pb-c.h"
void   verteilen2__vault__data_bool_entry__init
                     (Verteilen2__Vault__DataBoolEntry         *message)
{
  static const Verteilen2__Vault__DataBoolEntry init_value = VERTEILEN2__VAULT__DATA_BOOL_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__vault__data_int32_entry__init
                     (Verteilen2__Vault__DataInt32Entry         *message)
{
  static const Verteilen2__Vault__DataInt32Entry init_value = VERTEILEN2__VAULT__DATA_INT32_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__vault__data_int64_entry__init
                     (Verteilen2__Vault__DataInt64Entry         *message)
{
  static const Verteilen2__Vault__DataInt64Entry init_value = VERTEILEN2__VAULT__DATA_INT64_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__vault__data_float_entry__init
                     (Verteilen2__Vault__DataFloatEntry         *message)
{
  static const Verteilen2__Vault__DataFloatEntry init_value = VERTEILEN2__VAULT__DATA_FLOAT_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__vault__data_double_entry__init
                     (Verteilen2__Vault__DataDoubleEntry         *message)
{
  static const Verteilen2__Vault__DataDoubleEntry init_value = VERTEILEN2__VAULT__DATA_DOUBLE_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__vault__data_string_entry__init
                     (Verteilen2__Vault__DataStringEntry         *message)
{
  static const Verteilen2__Vault__DataStringEntry init_value = VERTEILEN2__VAULT__DATA_STRING_ENTRY__INIT;
  *message = init_value;
}
void   verteilen2__vault__init
                     (Verteilen2__Vault         *message)
{
  static const Verteilen2__Vault init_value = VERTEILEN2__VAULT__INIT;
  *message = init_value;
}
size_t verteilen2__vault__get_packed_size
                     (const Verteilen2__Vault *message)
{
  assert(message->base.descriptor == &verteilen2__vault__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t verteilen2__vault__pack
                     (const Verteilen2__Vault *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &verteilen2__vault__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t verteilen2__vault__pack_to_buffer
                     (const Verteilen2__Vault *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &verteilen2__vault__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Verteilen2__Vault *
       verteilen2__vault__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Verteilen2__Vault *)
     protobuf_c_message_unpack (&verteilen2__vault__descriptor,
                                allocator, len, data);
}
void   verteilen2__vault__free_unpacked
                     (Verteilen2__Vault *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &verteilen2__vault__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor verteilen2__vault__data_bool_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataBoolEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataBoolEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__vault__data_bool_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__vault__data_bool_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__vault__data_bool_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.Vault.DataBoolEntry",
  "DataBoolEntry",
  "Verteilen2__Vault__DataBoolEntry",
  "verteilen2",
  sizeof(Verteilen2__Vault__DataBoolEntry),
  2,
  verteilen2__vault__data_bool_entry__field_descriptors,
  verteilen2__vault__data_bool_entry__field_indices_by_name,
  1,  verteilen2__vault__data_bool_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__vault__data_bool_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__vault__data_int32_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataInt32Entry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataInt32Entry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__vault__data_int32_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__vault__data_int32_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__vault__data_int32_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.Vault.DataInt32Entry",
  "DataInt32Entry",
  "Verteilen2__Vault__DataInt32Entry",
  "verteilen2",
  sizeof(Verteilen2__Vault__DataInt32Entry),
  2,
  verteilen2__vault__data_int32_entry__field_descriptors,
  verteilen2__vault__data_int32_entry__field_indices_by_name,
  1,  verteilen2__vault__data_int32_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__vault__data_int32_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__vault__data_int64_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataInt64Entry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataInt64Entry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__vault__data_int64_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__vault__data_int64_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__vault__data_int64_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.Vault.DataInt64Entry",
  "DataInt64Entry",
  "Verteilen2__Vault__DataInt64Entry",
  "verteilen2",
  sizeof(Verteilen2__Vault__DataInt64Entry),
  2,
  verteilen2__vault__data_int64_entry__field_descriptors,
  verteilen2__vault__data_int64_entry__field_indices_by_name,
  1,  verteilen2__vault__data_int64_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__vault__data_int64_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__vault__data_float_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataFloatEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataFloatEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__vault__data_float_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__vault__data_float_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__vault__data_float_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.Vault.DataFloatEntry",
  "DataFloatEntry",
  "Verteilen2__Vault__DataFloatEntry",
  "verteilen2",
  sizeof(Verteilen2__Vault__DataFloatEntry),
  2,
  verteilen2__vault__data_float_entry__field_descriptors,
  verteilen2__vault__data_float_entry__field_indices_by_name,
  1,  verteilen2__vault__data_float_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__vault__data_float_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__vault__data_double_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataDoubleEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataDoubleEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__vault__data_double_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__vault__data_double_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__vault__data_double_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.Vault.DataDoubleEntry",
  "DataDoubleEntry",
  "Verteilen2__Vault__DataDoubleEntry",
  "verteilen2",
  sizeof(Verteilen2__Vault__DataDoubleEntry),
  2,
  verteilen2__vault__data_double_entry__field_descriptors,
  verteilen2__vault__data_double_entry__field_indices_by_name,
  1,  verteilen2__vault__data_double_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__vault__data_double_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__vault__data_string_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataStringEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault__DataStringEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__vault__data_string_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange verteilen2__vault__data_string_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verteilen2__vault__data_string_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.Vault.DataStringEntry",
  "DataStringEntry",
  "Verteilen2__Vault__DataStringEntry",
  "verteilen2",
  sizeof(Verteilen2__Vault__DataStringEntry),
  2,
  verteilen2__vault__data_string_entry__field_descriptors,
  verteilen2__vault__data_string_entry__field_indices_by_name,
  1,  verteilen2__vault__data_string_entry__number_ranges,
  (ProtobufCMessageInit) verteilen2__vault__data_string_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verteilen2__vault__field_descriptors[8] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verteilen2__Vault, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_bool",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__Vault, n_data_bool),
    offsetof(Verteilen2__Vault, data_bool),
    &verteilen2__vault__data_bool_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_int32",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__Vault, n_data_int32),
    offsetof(Verteilen2__Vault, data_int32),
    &verteilen2__vault__data_int32_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_int64",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__Vault, n_data_int64),
    offsetof(Verteilen2__Vault, data_int64),
    &verteilen2__vault__data_int64_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_float",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__Vault, n_data_float),
    offsetof(Verteilen2__Vault, data_float),
    &verteilen2__vault__data_float_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_double",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__Vault, n_data_double),
    offsetof(Verteilen2__Vault, data_double),
    &verteilen2__vault__data_double_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_string",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Verteilen2__Vault, n_data_string),
    offsetof(Verteilen2__Vault, data_string),
    &verteilen2__vault__data_string_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verteilen2__vault__field_indices_by_name[] = {
  2,   /* field[2] = data_bool */
  6,   /* field[6] = data_double */
  5,   /* field[5] = data_float */
  3,   /* field[3] = data_int32 */
  4,   /* field[4] = data_int64 */
  7,   /* field[7] = data_string */
  1,   /* field[1] = name */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange verteilen2__vault__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor verteilen2__vault__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "verteilen2.Vault",
  "Vault",
  "Verteilen2__Vault",
  "verteilen2",
  sizeof(Verteilen2__Vault),
  8,
  verteilen2__vault__field_descriptors,
  verteilen2__vault__field_indices_by_name,
  1,  verteilen2__vault__number_ranges,
  (ProtobufCMessageInit) verteilen2__vault__init,
  NULL,NULL,NULL    /* reserved[123] */
};
